Update centralized-deployment.md
OfficeDev/office-js-docs-pr pull request #2186
Opened 2020-09-17 01:00 UTC by mattgeim

Updating SSO in centralized deployment, removing preview status.

2020-09-17 01:01 UTC, o365devx commented
Docs Build status updates of commit _[c9fbd0b](https://github.com/OfficeDev/office-js-docs-pr/commits/c9fbd0b7c8a1fb66d93dce42e3a8498c0e979377)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/publish/centralized-deployment.md](https://github.com/OfficeDev/office-js-docs-pr/blob/mattgeim-patch-1/docs/publish/centralized-deployment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/publish/centralized-deployment?branch=pr-en-us-2186) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C17%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C202009170100216022-2186%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=at5ls%2BHs6pfQo1KWX8IVNIUFZ7slDEhgA0YTBUBrfA0%3D&st=2020-09-17T00%3A56%3A00Z&se=2020-10-18T01%3A01%3A00Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/57856ef7-e8cf-54ca-0d12-df5f42d1e8bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-21 18:02 UTC, davidchesnut requested changes
Looks good, just a couple typos...

2020-09-21 18:02 UTC, davidchesnut commented on docs/publish/centralized-deployment.md
> +    > Add-ins that utilize [single sign-on (SSO)](../develop/sso-in-office-add-ins.md) will prompt the admin to consent to the scopes listed in the add-in manifest.  If the same backing service is us
```suggestion
    > Add-ins that utilize [single sign-on (SSO)](../develop/sso-in-office-add-ins.md) will prompt the admin to consent to the scopes listed in the add-in manifest.  If the same backing service is used across multiple add-ins (the same Azure App ID is used with SSO in different add-ins), the scopes for each add-in will be prompted for consent with each deployment. This page will also display the list of permissions that the add-in requires.
```

2020-09-21 19:30 UTC, o365devx commented
Docs Build status updates of commit _[8829552](https://github.com/OfficeDev/office-js-docs-pr/commits/8829552f362a1c196674d17186daac6cf763d4d6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/publish/centralized-deployment.md](https://github.com/OfficeDev/office-js-docs-pr/blob/mattgeim-patch-1/docs/publish/centralized-deployment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/publish/centralized-deployment?branch=pr-en-us-2186) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C9%5C21%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C202009211929401853-2186%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=KGO4JFHL%2FrYbcoeo%2B3XPq2Bv2LKb3ps5AagIQFpAdfA%3D&st=2020-09-21T19%3A25%3A14Z&se=2020-10-22T19%3A30%3A14Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/57856ef7-e8cf-54ca-0d12-df5f42d1e8bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-09-21 20:58 UTC, davidchesnut approved these changes
Looks good!

2020-09-21 20:58 UTC, merged