Keyboard shortcuts in Office add-ins
OfficeDev/office-js-docs-pr pull request #2271
Opened 2020-10-16 23:11 UTC by Rick-Kirkham

A "how to" for keyboard shortcuts and extensive related manifest updates. 

REVIEWERS PLEASE NOTE: Most of the complications in the manifest about tokens and overrides are completely unmentioned in the "how to". This is a deliberate choice for purposes of the public preview because explaining all those complications would take an extensive "how to" in itself and there isn't likely to be time to create it in this quarter.  But we didn't want the new/revised manifest reference to tell any lies either, so these things are documented in the manifest reference docs. 

Relatively small changes/corrections can be made as comments to this PR. Requests for complete reorganizing or entirely new articles should be made as an email to me.

2020-10-16 23:12 UTC, o365devx commented
Docs Build status updates of commit _[c51fe08](https://github.com/OfficeDev/office-js-docs-pr/commits/c51fe0858822cc9360c648ddefd8296bc684de0f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/design/keyboard-shortcuts.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/design/keyboard-shortcuts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/design/keyboard-shortcuts?branch=pr-en-us-2271) |
[docs/develop/manifest-element-ordering.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/develop/manifest-element-ordering.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/manifest-element-ordering?branch=pr-en-us-2271) |
[docs/reference/manifest/extendedoverrides.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/extendedoverrides.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/extendedoverrides?branch=pr-en-us-2271) |
[docs/reference/manifest/functionfile.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/functionfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/functionfile?branch=pr-en-us-2271) |
[docs/reference/manifest/officeapp.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/officeapp.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/officeapp?branch=pr-en-us-2271) |
[docs/reference/manifest/override.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/override.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/override?branch=pr-en-us-2271) |
[docs/reference/manifest/token.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/token.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/token?branch=pr-en-us-2271) |
[docs/reference/manifest/tokens.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/tokens.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/tokens?branch=pr-en-us-2271) |
[docs/toc.yml](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/design/keyboard-shortcuts?branch=pr-en-us-2271) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C16%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C202010162311406940-2271%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=n%2BwZNkcIX6t9lfOwJk2q042vkYiz5zLw4E6GXa1g408%3D&st=2020-10-16T23%3A07%3A26Z&se=2020-11-16T23%3A12%3A26Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/57856ef7-e8cf-54ca-0d12-df5f42d1e8bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-20 18:06 UTC, AbidRahman-MSFT commented on docs/design/keyboard-shortcuts.md
> +1. In the JavaScript file, use calls of the [Office.actions.associate](/javascript/api/office/office.actions#associate) API to map a function to each action name that you used in the JSON file. To be
".. map a function to each action id that you used.."

2020-10-20 18:06 UTC, AbidRahman-MSFT commented on docs/design/keyboard-shortcuts.md
> +    - The first parameter is one of the action names from the JSON file.
The first parameter is one of the action ids from the JSON file

2020-10-20 18:06 UTC, AbidRahman-MSFT commented on docs/design/keyboard-shortcuts.md
> +    - The second parameter is the function that runs when a user presses the key combination that is mapped to the action name in the JSON file.
action ID

2020-10-20 18:10 UTC, AbidRahman-MSFT commented on docs/design/keyboard-shortcuts.md
> +There are four major steps to adding keyboard shortcuts to an add-in:
There are three major steps

2020-10-20 18:11 UTC, AbidRahman-MSFT commented on docs/design/keyboard-shortcuts.md
> +1. Create or edit the extended overrides JSON file to map action names to keyboard combinations.
we shouldn't refer to actions as 'action names', let's just use "actions" instead. 

Change "..map action names to keyboard combinations.." to "..map actions to keyboard combinations.."

2020-10-20 18:20 UTC, AbidRahman-MSFT commented on docs/design/keyboard-shortcuts.md
> +1. Add one or more runtime calls of the [Office.actions.associate](/javascript/api/office/office.actions#associate) API to map a function to each action name.
Change "...to each action name." to "each action"

2020-10-22 03:17 UTC, hjkim71 requested changes

2020-10-22 03:17 UTC, hjkim71 commented on docs/design/keyboard-shortcuts.md
> +1. Optionally, you can vary the key combination for Office on the web, Office on Windows, or Office on Mac with additional properties on the `"key"` property. The following is an example. The `"defau
OPTION key is also possible on Mac. Note that the modifiers are NOT case-sensitive.

2020-10-22 03:17 UTC, hjkim71 commented on docs/design/keyboard-shortcuts.md
> +- If you need more keyboard shortcuts, check the [list of Excel keyboard shortcuts](https://support.microsoft.com/office/keyboard-shortcuts-in-excel-1798d9d5-842a-42b8-9c99-9b7213f0040f), and avoid u
Actual list is different. Please refer to the following link. `c_mapStringToModifierKey` contains all the possible modifiers. `c_mapStringToVirtualKey` contains the possible other key. Note that any character in A-Z, a-z, 0-9 ranges is also possible for one other key.

https://dev.azure.com/office/_search?action=contents&text=ShortcutMappingTableManager.cpp&type=code&lp=custom-Collection&filters=ProjectFilters%7BOfficeSourceDepot%7DRepositoryFilters%7BOffice_devmain%7DBranchFilters%7Boffice_devmain%7D&pageSize=25&result=DefaultCollection%2FOfficeSourceDepot%2FOffice_devmain%2FGBOffice_devmain%2Fosfclient%2Fosfactions%2FShortcutMappingTableManager.cpp

2020-10-22 15:04 UTC, o365devx commented
Docs Build status updates of commit _[3af61e1](https://github.com/OfficeDev/office-js-docs-pr/commits/3af61e1f2aea77b2011f3515f79b8859c75eaf3c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/design/keyboard-shortcuts.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/design/keyboard-shortcuts.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/design/keyboard-shortcuts?branch=pr-en-us-2271) | [Details](#user-content-225336df-a7d7a3dd)
[docs/develop/manifest-element-ordering.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/develop/manifest-element-ordering.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/manifest-element-ordering?branch=pr-en-us-2271) |
[docs/reference/manifest/extendedoverrides.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/extendedoverrides.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/extendedoverrides?branch=pr-en-us-2271) |
[docs/reference/manifest/functionfile.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/functionfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/functionfile?branch=pr-en-us-2271) |
[docs/reference/manifest/officeapp.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/officeapp.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/officeapp?branch=pr-en-us-2271) |
[docs/reference/manifest/override.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/override.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/override?branch=pr-en-us-2271) |
[docs/reference/manifest/token.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/token.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/token?branch=pr-en-us-2271) |
[docs/reference/manifest/tokens.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/tokens.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/tokens?branch=pr-en-us-2271) |
[docs/toc.yml](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/design/keyboard-shortcuts?branch=pr-en-us-2271) |

<a id="225336df-a7d7a3dd"></a>
### [docs/design/keyboard-shortcuts.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/design/keyboard-shortcuts.md)
 - **Line 117, Column 1**: **[Suggestion-[code-block-indented](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Indented code blocks aren't allowed. Use a Markdown code block surrounded by triple backticks (```). NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 126, Column 1**: **[Suggestion-[code-block-indented](https://review.docs.microsoft.com/help/contribute/validation-ref/author-not-found?branch=main)]** `````Indented code blocks aren't allowed. Use a Markdown code block surrounded by triple backticks (```). NOTE: This Suggestion will become a Warning on 1/29/21.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C22%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C202010221503179711-2271%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=3Ssg3%2BTIYMS2fEZn3P%2FnatEhtfpM2RgJBG1Y8bwMPKo%3D&st=2020-10-22T14%3A59%3A01Z&se=2020-11-22T15%3A04%3A01Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/57856ef7-e8cf-54ca-0d12-df5f42d1e8bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-22 19:27 UTC, o365devx commented
Docs Build status updates of commit _[3090296](https://github.com/OfficeDev/office-js-docs-pr/commits/30902964d337e372b3794b23221e0012b063dc60)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/design/keyboard-shortcuts.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/design/keyboard-shortcuts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/design/keyboard-shortcuts?branch=pr-en-us-2271) |
[docs/develop/manifest-element-ordering.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/develop/manifest-element-ordering.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/manifest-element-ordering?branch=pr-en-us-2271) |
[docs/reference/manifest/extendedoverrides.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/extendedoverrides.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/extendedoverrides?branch=pr-en-us-2271) |
[docs/reference/manifest/functionfile.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/functionfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/functionfile?branch=pr-en-us-2271) |
[docs/reference/manifest/officeapp.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/officeapp.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/officeapp?branch=pr-en-us-2271) |
[docs/reference/manifest/override.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/override.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/override?branch=pr-en-us-2271) |
[docs/reference/manifest/token.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/token.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/token?branch=pr-en-us-2271) |
[docs/reference/manifest/tokens.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/tokens.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/tokens?branch=pr-en-us-2271) |
[docs/toc.yml](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/design/keyboard-shortcuts?branch=pr-en-us-2271) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C22%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C202010221926454410-2271%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=m8FrjtAViUX%2F56sFKJysbG11BVJAa3hcZR4Q0ysmUcM%3D&st=2020-10-22T19%3A22%3A26Z&se=2020-11-22T19%3A27%3A26Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/57856ef7-e8cf-54ca-0d12-df5f42d1e8bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-22 22:13 UTC, o365devx commented
Docs Build status updates of commit _[35f7f6a](https://github.com/OfficeDev/office-js-docs-pr/commits/35f7f6a7a17aae447aaae61f99c0cbac049cee31)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/design/keyboard-shortcuts.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/design/keyboard-shortcuts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/design/keyboard-shortcuts?branch=pr-en-us-2271) |
[docs/develop/manifest-element-ordering.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/develop/manifest-element-ordering.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/manifest-element-ordering?branch=pr-en-us-2271) |
[docs/reference/manifest/extendedoverrides.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/extendedoverrides.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/extendedoverrides?branch=pr-en-us-2271) |
[docs/reference/manifest/functionfile.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/functionfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/functionfile?branch=pr-en-us-2271) |
[docs/reference/manifest/officeapp.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/officeapp.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/officeapp?branch=pr-en-us-2271) |
[docs/reference/manifest/override.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/override.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/override?branch=pr-en-us-2271) |
[docs/reference/manifest/token.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/token.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/token?branch=pr-en-us-2271) |
[docs/reference/manifest/tokens.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/tokens.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/tokens?branch=pr-en-us-2271) |
[docs/toc.yml](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/design/keyboard-shortcuts?branch=pr-en-us-2271) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C22%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C202010222212569534-2271%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=0yjcrSAkj%2F3scO4MVL8PcQ0zDN4RwUjsAE5yvZLXK8I%3D&st=2020-10-22T22%3A08%3A31Z&se=2020-11-22T22%3A13%3A31Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/57856ef7-e8cf-54ca-0d12-df5f42d1e8bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-22 23:12 UTC, zlatko-michailov requested changes

2020-10-22 23:30 UTC, AlexJerabek commented on docs/design/keyboard-shortcuts.md
> +description: 'Learn how to add custom keyboard shortcuts, also known as key combinations, to your Office Add-in.'
"Office Add-in" is a brand term and must be capitalized like that. "add-in" as a stand-alone term is not a brand thing and is capitalized like any other noun.

2020-10-23 22:35 UTC, o365devx commented
Docs Build status updates of commit _[53b70e1](https://github.com/OfficeDev/office-js-docs-pr/commits/53b70e1670320647550c02741a8d864cf736edb4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/design/keyboard-shortcuts.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/design/keyboard-shortcuts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/design/keyboard-shortcuts?branch=pr-en-us-2271) |
[docs/develop/manifest-element-ordering.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/develop/manifest-element-ordering.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/manifest-element-ordering?branch=pr-en-us-2271) |
[docs/reference/manifest/extendedoverrides.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/extendedoverrides.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/extendedoverrides?branch=pr-en-us-2271) |
[docs/reference/manifest/functionfile.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/functionfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/functionfile?branch=pr-en-us-2271) |
[docs/reference/manifest/officeapp.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/officeapp.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/officeapp?branch=pr-en-us-2271) |
[docs/reference/manifest/override.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/override.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/override?branch=pr-en-us-2271) |
[docs/reference/manifest/token.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/token.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/token?branch=pr-en-us-2271) |
[docs/reference/manifest/tokens.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/tokens.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/tokens?branch=pr-en-us-2271) |
[docs/toc.yml](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/design/keyboard-shortcuts?branch=pr-en-us-2271) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C23%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C202010232234478084-2271%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=qqS9ABAFFgWwTSp81oZlSzL%2BZFFoipS0tP0PO22O9I8%3D&st=2020-10-23T22%3A30%3A23Z&se=2020-11-23T22%3A35%3A23Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/57856ef7-e8cf-54ca-0d12-df5f42d1e8bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-26 20:54 UTC, o365devx commented
Docs Build status updates of commit _[dc70bad](https://github.com/OfficeDev/office-js-docs-pr/commits/dc70badf135ecc299f0387b7b7ef98114bbd98e3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/design/keyboard-shortcuts.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/design/keyboard-shortcuts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/design/keyboard-shortcuts?branch=pr-en-us-2271) |
[docs/develop/manifest-element-ordering.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/develop/manifest-element-ordering.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/manifest-element-ordering?branch=pr-en-us-2271) |
[docs/reference/manifest/extendedoverrides.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/extendedoverrides.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/extendedoverrides?branch=pr-en-us-2271) |
[docs/reference/manifest/functionfile.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/functionfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/functionfile?branch=pr-en-us-2271) |
[docs/reference/manifest/officeapp.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/officeapp.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/officeapp?branch=pr-en-us-2271) |
[docs/reference/manifest/override.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/override.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/override?branch=pr-en-us-2271) |
[docs/reference/manifest/token.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/token.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/token?branch=pr-en-us-2271) |
[docs/reference/manifest/tokens.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/tokens.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/tokens?branch=pr-en-us-2271) |
[docs/toc.yml](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/design/keyboard-shortcuts?branch=pr-en-us-2271) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C26%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C202010262053545822-2271%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=NPCntDBUt8ZVDL5w3YpGHGUez5PkoEXiTOKQKIB5m38%3D&st=2020-10-26T20%3A49%3A30Z&se=2020-11-26T20%3A54%3A30Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/57856ef7-e8cf-54ca-0d12-df5f42d1e8bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-26 20:55 UTC, o365devx commented
Docs Build status updates of commit _[38ba758](https://github.com/OfficeDev/office-js-docs-pr/commits/38ba7586100bfd91c57ed414b6a9335170457709)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/design/keyboard-shortcuts.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/design/keyboard-shortcuts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/design/keyboard-shortcuts?branch=pr-en-us-2271) |
[docs/develop/manifest-element-ordering.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/develop/manifest-element-ordering.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/manifest-element-ordering?branch=pr-en-us-2271) |
[docs/reference/manifest/extendedoverrides.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/extendedoverrides.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/extendedoverrides?branch=pr-en-us-2271) |
[docs/reference/manifest/functionfile.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/functionfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/functionfile?branch=pr-en-us-2271) |
[docs/reference/manifest/officeapp.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/officeapp.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/officeapp?branch=pr-en-us-2271) |
[docs/reference/manifest/override.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/override.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/override?branch=pr-en-us-2271) |
[docs/reference/manifest/token.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/token.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/token?branch=pr-en-us-2271) |
[docs/reference/manifest/tokens.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/tokens.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/tokens?branch=pr-en-us-2271) |
[docs/toc.yml](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/design/keyboard-shortcuts?branch=pr-en-us-2271) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C26%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C202010262054417660-2271%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=t9iseIZoeYVphsgQlEfd9pQtnGvFKteOobSCT5gRYGA%3D&st=2020-10-26T20%3A50%3A22Z&se=2020-11-26T20%3A55%3A22Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/57856ef7-e8cf-54ca-0d12-df5f42d1e8bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-06 20:08 UTC, o365devx commented
Docs Build status updates of commit _[1431d92](https://github.com/OfficeDev/office-js-docs-pr/commits/1431d920678afc9b86f879a8656c6cce8fbe6bc6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/design/keyboard-shortcuts.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/design/keyboard-shortcuts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/design/keyboard-shortcuts?branch=pr-en-us-2271) |
[docs/develop/manifest-element-ordering.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/develop/manifest-element-ordering.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/manifest-element-ordering?branch=pr-en-us-2271) |
[docs/excel/configure-your-add-in-to-use-a-shared-runtime.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/excel/configure-your-add-in-to-use-a-shared-runtime.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/configure-your-add-in-to-use-a-shared-runtime?branch=pr-en-us-2271) |
[docs/includes/keyboard-shortcuts-prerequisites.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/includes/keyboard-shortcuts-prerequisites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/design/keyboard-shortcuts?branch=pr-en-us-2271) |
[docs/reference/manifest/extendedoverrides.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/extendedoverrides.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/extendedoverrides?branch=pr-en-us-2271) |
[docs/reference/manifest/functionfile.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/functionfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/functionfile?branch=pr-en-us-2271) |
[docs/reference/manifest/officeapp.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/officeapp.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/officeapp?branch=pr-en-us-2271) |
[docs/reference/manifest/override.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/override.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/override?branch=pr-en-us-2271) |
[docs/reference/manifest/token.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/token.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/token?branch=pr-en-us-2271) |
[docs/reference/manifest/tokens.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/tokens.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/tokens?branch=pr-en-us-2271) |
[docs/toc.yml](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/design/keyboard-shortcuts?branch=pr-en-us-2271) |
[docs/tutorials/keyboard-shortcuts-tutorial.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/tutorials/keyboard-shortcuts-tutorial.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/tutorials/keyboard-shortcuts-tutorial?branch=pr-en-us-2271) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C6%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C202011062007569560-2271%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=L9228Togy%2Bv4EpNEM7P%2ByjMpJaaKe1Or3I7K31sNbsw%3D&st=2020-11-06T20%3A03%3A34Z&se=2020-12-07T20%3A08%3A34Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/57856ef7-e8cf-54ca-0d12-df5f42d1e8bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-06 22:14 UTC, o365devx commented
Docs Build status updates of commit _[adf2a92](https://github.com/OfficeDev/office-js-docs-pr/commits/adf2a92b1fa70e451cc1b8ec48b049e475e0ce66)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/design/keyboard-shortcuts.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/design/keyboard-shortcuts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/design/keyboard-shortcuts?branch=pr-en-us-2271) |
[docs/develop/manifest-element-ordering.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/develop/manifest-element-ordering.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/manifest-element-ordering?branch=pr-en-us-2271) |
[docs/excel/configure-your-add-in-to-use-a-shared-runtime.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/excel/configure-your-add-in-to-use-a-shared-runtime.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/configure-your-add-in-to-use-a-shared-runtime?branch=pr-en-us-2271) |
[docs/includes/keyboard-shortcuts-prerequisites.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/includes/keyboard-shortcuts-prerequisites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/design/keyboard-shortcuts?branch=pr-en-us-2271) |
[docs/reference/manifest/extendedoverrides.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/extendedoverrides.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/extendedoverrides?branch=pr-en-us-2271) |
[docs/reference/manifest/functionfile.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/functionfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/functionfile?branch=pr-en-us-2271) |
[docs/reference/manifest/officeapp.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/officeapp.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/officeapp?branch=pr-en-us-2271) |
[docs/reference/manifest/override.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/override.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/override?branch=pr-en-us-2271) |
[docs/reference/manifest/token.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/token.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/token?branch=pr-en-us-2271) |
[docs/reference/manifest/tokens.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/tokens.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/tokens?branch=pr-en-us-2271) |
[docs/toc.yml](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/design/keyboard-shortcuts?branch=pr-en-us-2271) |
[docs/tutorials/keyboard-shortcuts-tutorial.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/tutorials/keyboard-shortcuts-tutorial.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/tutorials/keyboard-shortcuts-tutorial?branch=pr-en-us-2271) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C6%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C202011062214137682-2271%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=srV%2BkL92vb0wc00RPtTKQHFcdg0HADFhv6UX%2FnVKOpQ%3D&st=2020-11-06T22%3A09%3A53Z&se=2020-12-07T22%3A14%3A53Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/57856ef7-e8cf-54ca-0d12-df5f42d1e8bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-06 22:22 UTC, o365devx commented
Docs Build status updates of commit _[c1823f6](https://github.com/OfficeDev/office-js-docs-pr/commits/c1823f6bd5dd7518a2bd631f48e4d4b5903f75e8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/design/keyboard-shortcuts.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/design/keyboard-shortcuts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/design/keyboard-shortcuts?branch=pr-en-us-2271) |
[docs/develop/manifest-element-ordering.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/develop/manifest-element-ordering.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/manifest-element-ordering?branch=pr-en-us-2271) |
[docs/excel/configure-your-add-in-to-use-a-shared-runtime.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/excel/configure-your-add-in-to-use-a-shared-runtime.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/configure-your-add-in-to-use-a-shared-runtime?branch=pr-en-us-2271) |
[docs/includes/keyboard-shortcuts-prerequisites.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/includes/keyboard-shortcuts-prerequisites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/design/keyboard-shortcuts?branch=pr-en-us-2271) |
[docs/reference/manifest/extendedoverrides.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/extendedoverrides.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/extendedoverrides?branch=pr-en-us-2271) |
[docs/reference/manifest/functionfile.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/functionfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/functionfile?branch=pr-en-us-2271) |
[docs/reference/manifest/officeapp.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/officeapp.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/officeapp?branch=pr-en-us-2271) |
[docs/reference/manifest/override.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/override.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/override?branch=pr-en-us-2271) |
[docs/reference/manifest/token.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/token.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/token?branch=pr-en-us-2271) |
[docs/reference/manifest/tokens.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/tokens.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/tokens?branch=pr-en-us-2271) |
[docs/toc.yml](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/design/keyboard-shortcuts?branch=pr-en-us-2271) |
[docs/tutorials/keyboard-shortcuts-tutorial.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/tutorials/keyboard-shortcuts-tutorial.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/tutorials/keyboard-shortcuts-tutorial?branch=pr-en-us-2271) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C6%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C202011062222126683-2271%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=r3b0wS9Ww5c77bPHEC0nwK41Y4bFIcVFyD6ApDb7Qow%3D&st=2020-11-06T22%3A17%3A48Z&se=2020-12-07T22%3A22%3A48Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/57856ef7-e8cf-54ca-0d12-df5f42d1e8bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-06 22:53 UTC, o365devx commented
Docs Build status updates of commit _[a9d8c51](https://github.com/OfficeDev/office-js-docs-pr/commits/a9d8c512a05c2f20024a35b88681ea4b5a5865a6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/design/keyboard-shortcuts.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/design/keyboard-shortcuts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/design/keyboard-shortcuts?branch=pr-en-us-2271) |
[docs/develop/manifest-element-ordering.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/develop/manifest-element-ordering.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/manifest-element-ordering?branch=pr-en-us-2271) |
[docs/excel/configure-your-add-in-to-use-a-shared-runtime.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/excel/configure-your-add-in-to-use-a-shared-runtime.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/configure-your-add-in-to-use-a-shared-runtime?branch=pr-en-us-2271) |
[docs/includes/keyboard-shortcuts-prerequisites.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/includes/keyboard-shortcuts-prerequisites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/design/keyboard-shortcuts?branch=pr-en-us-2271) |
[docs/reference/manifest/extendedoverrides.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/extendedoverrides.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/extendedoverrides?branch=pr-en-us-2271) |
[docs/reference/manifest/functionfile.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/functionfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/functionfile?branch=pr-en-us-2271) |
[docs/reference/manifest/officeapp.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/officeapp.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/officeapp?branch=pr-en-us-2271) |
[docs/reference/manifest/override.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/override.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/override?branch=pr-en-us-2271) |
[docs/reference/manifest/token.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/token.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/token?branch=pr-en-us-2271) |
[docs/reference/manifest/tokens.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/tokens.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/tokens?branch=pr-en-us-2271) |
[docs/toc.yml](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/design/keyboard-shortcuts?branch=pr-en-us-2271) |
[docs/tutorials/keyboard-shortcuts-tutorial.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/tutorials/keyboard-shortcuts-tutorial.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/tutorials/keyboard-shortcuts-tutorial?branch=pr-en-us-2271) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C6%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C202011062252290767-2271%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=4EiUQ%2BXKaA4%2BwuMcf2D2dDyxmrLe9VsoHYAfu6QE6oo%3D&st=2020-11-06T22%3A48%3A08Z&se=2020-12-07T22%3A53%3A08Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/57856ef7-e8cf-54ca-0d12-df5f42d1e8bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-06 23:37 UTC, o365devx commented
Docs Build status updates of commit _[d999e71](https://github.com/OfficeDev/office-js-docs-pr/commits/d999e713b59a6c25518c701d90205243fd2af431)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/design/keyboard-shortcuts.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/design/keyboard-shortcuts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/design/keyboard-shortcuts?branch=pr-en-us-2271) |
[docs/develop/manifest-element-ordering.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/develop/manifest-element-ordering.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/manifest-element-ordering?branch=pr-en-us-2271) |
[docs/excel/configure-your-add-in-to-use-a-shared-runtime.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/excel/configure-your-add-in-to-use-a-shared-runtime.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/configure-your-add-in-to-use-a-shared-runtime?branch=pr-en-us-2271) |
[docs/includes/keyboard-shortcuts-prerequisites.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/includes/keyboard-shortcuts-prerequisites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/design/keyboard-shortcuts?branch=pr-en-us-2271) |
[docs/reference/manifest/extendedoverrides.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/extendedoverrides.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/extendedoverrides?branch=pr-en-us-2271) |
[docs/reference/manifest/functionfile.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/functionfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/functionfile?branch=pr-en-us-2271) |
[docs/reference/manifest/officeapp.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/officeapp.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/officeapp?branch=pr-en-us-2271) |
[docs/reference/manifest/override.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/override.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/override?branch=pr-en-us-2271) |
[docs/reference/manifest/token.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/token.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/token?branch=pr-en-us-2271) |
[docs/reference/manifest/tokens.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/tokens.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/tokens?branch=pr-en-us-2271) |
[docs/toc.yml](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/design/keyboard-shortcuts?branch=pr-en-us-2271) |
[docs/tutorials/keyboard-shortcuts-tutorial.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/tutorials/keyboard-shortcuts-tutorial.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/tutorials/keyboard-shortcuts-tutorial?branch=pr-en-us-2271) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C6%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C202011062337152201-2271%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=zX0NKGMGI7mKapCsHk%2B6WERFo1vzFs44voLl%2B7YGrLk%3D&st=2020-11-06T23%3A32%3A57Z&se=2020-12-07T23%3A37%3A57Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/57856ef7-e8cf-54ca-0d12-df5f42d1e8bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-07 23:46 UTC, o365devx commented
Docs Build status updates of commit _[1cda66d](https://github.com/OfficeDev/office-js-docs-pr/commits/1cda66de1e2237484f7a5bab7c3eaf58e20f29c3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/design/keyboard-shortcuts.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/design/keyboard-shortcuts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/design/keyboard-shortcuts?branch=pr-en-us-2271) |
[docs/develop/manifest-element-ordering.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/develop/manifest-element-ordering.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/manifest-element-ordering?branch=pr-en-us-2271) |
[docs/excel/configure-your-add-in-to-use-a-shared-runtime.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/excel/configure-your-add-in-to-use-a-shared-runtime.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/configure-your-add-in-to-use-a-shared-runtime?branch=pr-en-us-2271) |
[docs/includes/keyboard-shortcuts-prerequisites.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/includes/keyboard-shortcuts-prerequisites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/design/keyboard-shortcuts?branch=pr-en-us-2271) |
[docs/reference/manifest/extendedoverrides.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/extendedoverrides.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/extendedoverrides?branch=pr-en-us-2271) |
[docs/reference/manifest/functionfile.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/functionfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/functionfile?branch=pr-en-us-2271) |
[docs/reference/manifest/officeapp.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/officeapp.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/officeapp?branch=pr-en-us-2271) |
[docs/reference/manifest/override.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/override.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/override?branch=pr-en-us-2271) |
[docs/reference/manifest/token.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/token.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/token?branch=pr-en-us-2271) |
[docs/reference/manifest/tokens.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/tokens.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/tokens?branch=pr-en-us-2271) |
[docs/toc.yml](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/design/keyboard-shortcuts?branch=pr-en-us-2271) |
[docs/tutorials/keyboard-shortcuts-tutorial.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/tutorials/keyboard-shortcuts-tutorial.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/tutorials/keyboard-shortcuts-tutorial?branch=pr-en-us-2271) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C7%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C202011072346168195-2271%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=j%2FMhrQXei%2Fe7fbattLfa7i5kpzSOaNB8q9S6VJHRl7Q%3D&st=2020-11-07T23%3A41%3A57Z&se=2020-12-08T23%3A46%3A57Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/57856ef7-e8cf-54ca-0d12-df5f42d1e8bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-09 21:12 UTC, o365devx commented
Docs Build status updates of commit _[0f9f3af](https://github.com/OfficeDev/office-js-docs-pr/commits/0f9f3af1ef1fed7b19f82ed07a1e08fe489135ea)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/design/keyboard-shortcuts.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/design/keyboard-shortcuts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/design/keyboard-shortcuts?branch=pr-en-us-2271) |
[docs/develop/manifest-element-ordering.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/develop/manifest-element-ordering.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/manifest-element-ordering?branch=pr-en-us-2271) |
[docs/excel/configure-your-add-in-to-use-a-shared-runtime.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/excel/configure-your-add-in-to-use-a-shared-runtime.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/configure-your-add-in-to-use-a-shared-runtime?branch=pr-en-us-2271) |
[docs/includes/keyboard-shortcuts-prerequisites.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/includes/keyboard-shortcuts-prerequisites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/design/keyboard-shortcuts?branch=pr-en-us-2271) |
[docs/reference/manifest/extendedoverrides.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/extendedoverrides.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/extendedoverrides?branch=pr-en-us-2271) |
[docs/reference/manifest/functionfile.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/functionfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/functionfile?branch=pr-en-us-2271) |
[docs/reference/manifest/officeapp.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/officeapp.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/officeapp?branch=pr-en-us-2271) |
[docs/reference/manifest/override.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/override.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/override?branch=pr-en-us-2271) |
[docs/reference/manifest/token.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/token.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/token?branch=pr-en-us-2271) |
[docs/reference/manifest/tokens.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/tokens.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/tokens?branch=pr-en-us-2271) |
[docs/toc.yml](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/design/keyboard-shortcuts?branch=pr-en-us-2271) |
[docs/tutorials/keyboard-shortcuts-tutorial.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/tutorials/keyboard-shortcuts-tutorial.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/tutorials/keyboard-shortcuts-tutorial?branch=pr-en-us-2271) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C9%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C202011092111406434-2271%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=6ml4E5ii4bpXSVVjzMhJUnT1GslV8UqsGK5AiDLq1Y0%3D&st=2020-11-09T21%3A07%3A17Z&se=2020-12-10T21%3A12%3A17Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/57856ef7-e8cf-54ca-0d12-df5f42d1e8bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-10 00:10 UTC, o365devx commented
Docs Build status updates of commit _[5561642](https://github.com/OfficeDev/office-js-docs-pr/commits/5561642df3de12e093df1a7d48668ead3f619df0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/excel/configure-your-add-in-to-use-a-shared-runtime.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/excel/configure-your-add-in-to-use-a-shared-runtime.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/configure-your-add-in-to-use-a-shared-runtime?branch=pr-en-us-2271) | [Details](#user-content-063dae14-c1662132)
[docs/design/keyboard-shortcuts.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/design/keyboard-shortcuts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/design/keyboard-shortcuts?branch=pr-en-us-2271) |
[docs/develop/manifest-element-ordering.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/develop/manifest-element-ordering.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/manifest-element-ordering?branch=pr-en-us-2271) |
[docs/includes/keyboard-shortcuts-prerequisites.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/includes/keyboard-shortcuts-prerequisites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/design/keyboard-shortcuts?branch=pr-en-us-2271) |
[docs/reference/manifest/extendedoverrides.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/extendedoverrides.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/extendedoverrides?branch=pr-en-us-2271) |
[docs/reference/manifest/functionfile.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/functionfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/functionfile?branch=pr-en-us-2271) |
[docs/reference/manifest/officeapp.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/officeapp.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/officeapp?branch=pr-en-us-2271) |
[docs/reference/manifest/override.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/override.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/override?branch=pr-en-us-2271) |
[docs/reference/manifest/token.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/token.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/token?branch=pr-en-us-2271) |
[docs/reference/manifest/tokens.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/tokens.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/tokens?branch=pr-en-us-2271) |
[docs/toc.yml](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/design/keyboard-shortcuts?branch=pr-en-us-2271) |

<a id="063dae14-c1662132"></a>
### [docs/excel/configure-your-add-in-to-use-a-shared-runtime.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/excel/configure-your-add-in-to-use-a-shared-runtime.md)
 - **Line 138, Column 14**: **[Warning-file-not-found]** `````Invalid file link: '../tutorials/keyboard-shortcuts-tutorial.md'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C10%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C202011100009569462-2271%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=RUmW3C9U7LvzFwhGuYMkMleKlyfG3Jt9%2BBD2ldEue1k%3D&st=2020-11-10T00%3A05%3A34Z&se=2020-12-11T00%3A10%3A34Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/57856ef7-e8cf-54ca-0d12-df5f42d1e8bb?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-10 00:19 UTC, o365devx commented
Docs Build status updates of commit _[f46408c](https://github.com/OfficeDev/office-js-docs-pr/commits/f46408c017f90f1be02cee08756b4e41fb9c5b3a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/design/keyboard-shortcuts.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/design/keyboard-shortcuts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/design/keyboard-shortcuts?branch=pr-en-us-2271) |
[docs/develop/manifest-element-ordering.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/develop/manifest-element-ordering.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/manifest-element-ordering?branch=pr-en-us-2271) |
[docs/excel/configure-your-add-in-to-use-a-shared-runtime.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/excel/configure-your-add-in-to-use-a-shared-runtime.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/configure-your-add-in-to-use-a-shared-runtime?branch=pr-en-us-2271) |
[docs/includes/keyboard-shortcuts-prerequisites.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/includes/keyboard-shortcuts-prerequisites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/design/keyboard-shortcuts?branch=pr-en-us-2271) |
[docs/reference/manifest/extendedoverrides.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/extendedoverrides.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/extendedoverrides?branch=pr-en-us-2271) |
[docs/reference/manifest/functionfile.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/functionfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/functionfile?branch=pr-en-us-2271) |
[docs/reference/manifest/officeapp.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/officeapp.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/officeapp?branch=pr-en-us-2271) |
[docs/reference/manifest/override.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/override.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/override?branch=pr-en-us-2271) |
[docs/reference/manifest/token.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/token.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/token?branch=pr-en-us-2271) |
[docs/reference/manifest/tokens.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/tokens.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/tokens?branch=pr-en-us-2271) |
[docs/toc.yml](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/design/keyboard-shortcuts?branch=pr-en-us-2271) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C10%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C202011100018233639-2271%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=O25iuKrz0WkxfxmF%2FPWgJv9HugKKSr8%2BFjI89NIH8J4%3D&st=2020-11-10T00%3A14%3A57Z&se=2020-12-11T00%3A19%3A57Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/57856ef7-e8cf-54ca-0d12-df5f42d1e8bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-10 01:02 UTC, o365devx commented
Docs Build status updates of commit _[7c4f2a5](https://github.com/OfficeDev/office-js-docs-pr/commits/7c4f2a54ab9e107aa05fe9b11b31d9d008da84e3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/design/keyboard-shortcuts.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/design/keyboard-shortcuts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/design/keyboard-shortcuts?branch=pr-en-us-2271) |
[docs/develop/manifest-element-ordering.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/develop/manifest-element-ordering.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/manifest-element-ordering?branch=pr-en-us-2271) |
[docs/excel/configure-your-add-in-to-use-a-shared-runtime.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/excel/configure-your-add-in-to-use-a-shared-runtime.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/configure-your-add-in-to-use-a-shared-runtime?branch=pr-en-us-2271) |
[docs/includes/keyboard-shortcuts-prerequisites.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/includes/keyboard-shortcuts-prerequisites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/design/keyboard-shortcuts?branch=pr-en-us-2271) |
[docs/reference/manifest/extendedoverrides.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/extendedoverrides.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/extendedoverrides?branch=pr-en-us-2271) |
[docs/reference/manifest/functionfile.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/functionfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/functionfile?branch=pr-en-us-2271) |
[docs/reference/manifest/officeapp.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/officeapp.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/officeapp?branch=pr-en-us-2271) |
[docs/reference/manifest/override.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/override.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/override?branch=pr-en-us-2271) |
[docs/reference/manifest/token.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/token.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/token?branch=pr-en-us-2271) |
[docs/reference/manifest/tokens.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/tokens.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/tokens?branch=pr-en-us-2271) |
[docs/toc.yml](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/design/keyboard-shortcuts?branch=pr-en-us-2271) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C10%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C202011100102194071-2271%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=S4tthlhkJh9TIrRVFty3b3u%2BM5RkriH0nlA4Upr%2BoR4%3D&st=2020-11-10T00%3A57%3A51Z&se=2020-12-11T01%3A02%3A51Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/57856ef7-e8cf-54ca-0d12-df5f42d1e8bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-10 01:09 UTC, o365devx commented
Docs Build status updates of commit _[25313e2](https://github.com/OfficeDev/office-js-docs-pr/commits/25313e2f03d4e24b79bd27f6d5302e26e090efe9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/design/keyboard-shortcuts.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/design/keyboard-shortcuts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/design/keyboard-shortcuts?branch=pr-en-us-2271) |
[docs/develop/manifest-element-ordering.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/develop/manifest-element-ordering.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/manifest-element-ordering?branch=pr-en-us-2271) |
[docs/excel/configure-your-add-in-to-use-a-shared-runtime.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/excel/configure-your-add-in-to-use-a-shared-runtime.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/configure-your-add-in-to-use-a-shared-runtime?branch=pr-en-us-2271) |
[docs/includes/keyboard-shortcuts-prerequisites.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/includes/keyboard-shortcuts-prerequisites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/design/keyboard-shortcuts?branch=pr-en-us-2271) |
[docs/reference/manifest/extendedoverrides.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/extendedoverrides.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/extendedoverrides?branch=pr-en-us-2271) |
[docs/reference/manifest/functionfile.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/functionfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/functionfile?branch=pr-en-us-2271) |
[docs/reference/manifest/officeapp.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/officeapp.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/officeapp?branch=pr-en-us-2271) |
[docs/reference/manifest/override.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/override.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/override?branch=pr-en-us-2271) |
[docs/reference/manifest/token.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/token.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/token?branch=pr-en-us-2271) |
[docs/reference/manifest/tokens.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/tokens.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/tokens?branch=pr-en-us-2271) |
[docs/toc.yml](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/design/keyboard-shortcuts?branch=pr-en-us-2271) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C10%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C202011100108455817-2271%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=jC5w00ncmnU0xzMpMOUGMZ6NxlBqmQjLHJl%2BMufACms%3D&st=2020-11-10T01%3A04%3A20Z&se=2020-12-11T01%3A09%3A20Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/57856ef7-e8cf-54ca-0d12-df5f42d1e8bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-10 01:11 UTC, o365devx commented
Docs Build status updates of commit _[95d6db8](https://github.com/OfficeDev/office-js-docs-pr/commits/95d6db823bb9002bcfc2470b309d8eecc2e2d5dc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/design/keyboard-shortcuts.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/design/keyboard-shortcuts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/design/keyboard-shortcuts?branch=pr-en-us-2271) |
[docs/develop/manifest-element-ordering.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/develop/manifest-element-ordering.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/manifest-element-ordering?branch=pr-en-us-2271) |
[docs/excel/configure-your-add-in-to-use-a-shared-runtime.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/excel/configure-your-add-in-to-use-a-shared-runtime.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/configure-your-add-in-to-use-a-shared-runtime?branch=pr-en-us-2271) |
[docs/includes/keyboard-shortcuts-prerequisites.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/includes/keyboard-shortcuts-prerequisites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/design/keyboard-shortcuts?branch=pr-en-us-2271) |
[docs/reference/manifest/extendedoverrides.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/extendedoverrides.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/extendedoverrides?branch=pr-en-us-2271) |
[docs/reference/manifest/functionfile.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/functionfile.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/functionfile?branch=pr-en-us-2271) |
[docs/reference/manifest/officeapp.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/officeapp.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/officeapp?branch=pr-en-us-2271) |
[docs/reference/manifest/override.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/override.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/override?branch=pr-en-us-2271) |
[docs/reference/manifest/token.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/token.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/token?branch=pr-en-us-2271) |
[docs/reference/manifest/tokens.md](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/reference/manifest/tokens.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/tokens?branch=pr-en-us-2271) |
[docs/toc.yml](https://github.com/OfficeDev/office-js-docs-pr/blob/keyboard-shortcuts/docs/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/design/keyboard-shortcuts?branch=pr-en-us-2271) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C10%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C202011100111165498-2271%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=VXsCuTd16n1j78vq%2FltRyjJy1rgM5fm9RCPzFa1zGI4%3D&st=2020-11-10T01%3A06%3A51Z&se=2020-12-11T01%3A11%3A51Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/57856ef7-e8cf-54ca-0d12-df5f42d1e8bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-10 21:21 UTC, merged