[Excel] (Custom Functions) Clarify runtimes in UI-less debugging article
OfficeDev/office-js-docs-pr pull request #2612
Opened 2021-04-09 00:14 UTC by alison-mk

Updating article based on customer issue #2597.

2021-04-09 00:20 UTC, opbld30 commented
Docs Build status updates of commit _[aa30dad](https://github.com/OfficeDev/office-js-docs-pr/commits/aa30dadf39f799e8c4e666372547ccd365f6aed3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/excel/custom-functions-debugging.md](https://github.com/OfficeDev/office-js-docs-pr/blob/alison-mk-cf-ui-less-debugging/docs/excel/custom-functions-debugging.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-debugging?branch=pr-en-us-2612) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C9%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C202104090015030823-2612%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=3Etskhx0na0rtSNuhAOr%2F8SR84Qx2B9mXxoDnIcxB4A%3D&st=2021-04-09T00%3A15%3A24Z&se=2021-05-10T00%3A20%3A24Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/57856ef7-e8cf-54ca-0d12-df5f42d1e8bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-09 17:54 UTC, mscharlock commented on docs/excel/custom-functions-debugging.md
> +This debugging process only works for UI-less custom functions, which are custom functions that use the `OfficeRuntime` JavaScript runtime. This debugging process doesn't work with custom functions t
```suggestion
This debugging process only works for UI-less custom functions, which are custom functions that use the `OfficeRuntime` JavaScript runtime. This debugging process doesn't work with custom functions that use the `SharedRuntime` JavaScript runtime. 
```

2021-04-09 17:56 UTC, mscharlock commented on docs/excel/custom-functions-debugging.md
> +Debugging for custom functions that don't use a task pane or other user interface elements (UI-less custom functions) can be accomplished by multiple means, depending on what platform you're using.
```suggestion
This article discusses debugging *only* for custom functions that don't use a task pane or other user interface elements (UI-less custom functions). 
```

2021-04-09 18:09 UTC, mscharlock requested changes
Does this make sense? Happy to chat about it as well.

2021-04-10 00:27 UTC, opbld31 commented
Docs Build status updates of commit _[95e1fef](https://github.com/OfficeDev/office-js-docs-pr/commits/95e1fef2c4cb9c59bf9f2ebb32119fac8903d100)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/excel/custom-functions-debugging.md](https://github.com/OfficeDev/office-js-docs-pr/blob/alison-mk-cf-ui-less-debugging/docs/excel/custom-functions-debugging.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-debugging?branch=pr-en-us-2612) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C10%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C202104100026557788-2612%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=7VkG9e0%2FEx0h%2BiKhCXtwQeAZezMVzXMP9%2BuL1p3jS3o%3D&st=2021-04-10T00%3A22%3A36Z&se=2021-05-11T00%3A27%3A36Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/57856ef7-e8cf-54ca-0d12-df5f42d1e8bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-10 00:37 UTC, opbld32 commented
Docs Build status updates of commit _[519f449](https://github.com/OfficeDev/office-js-docs-pr/commits/519f449156913160e4a627c14c20702ebc77c426)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/excel/custom-functions-debugging.md](https://github.com/OfficeDev/office-js-docs-pr/blob/alison-mk-cf-ui-less-debugging/docs/excel/custom-functions-debugging.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-debugging?branch=pr-en-us-2612) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C10%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C202104100037185320-2612%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=WbEhO8hD1fwfjHe%2FDaBhE%2FW6g7rEvoaO5dqiQEg3glo%3D&st=2021-04-10T00%3A32%3A52Z&se=2021-05-11T00%3A37%3A52Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/57856ef7-e8cf-54ca-0d12-df5f42d1e8bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-10 00:40 UTC, opbld34 commented
Docs Build status updates of commit _[163c384](https://github.com/OfficeDev/office-js-docs-pr/commits/163c384808b613955e3c2501f9f52dcb64ba6e99)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/excel/custom-functions-debugging.md](https://github.com/OfficeDev/office-js-docs-pr/blob/alison-mk-cf-ui-less-debugging/docs/excel/custom-functions-debugging.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-debugging?branch=pr-en-us-2612) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C10%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C202104100039450060-2612%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2FmBuApQvSmbzk5UXQwo0DVw199COkWliPyPlvF3mm%2Fk%3D&st=2021-04-10T00%3A35%3A25Z&se=2021-05-11T00%3A40%3A25Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/57856ef7-e8cf-54ca-0d12-df5f42d1e8bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-10 00:43 UTC, opbld30 commented
Docs Build status updates of commit _[6de050b](https://github.com/OfficeDev/office-js-docs-pr/commits/6de050b825f442324e730d238e577c8a6bc95ad4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/excel/custom-functions-debugging.md](https://github.com/OfficeDev/office-js-docs-pr/blob/alison-mk-cf-ui-less-debugging/docs/excel/custom-functions-debugging.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-debugging?branch=pr-en-us-2612) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C10%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C202104100043129234-2612%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=fU%2F1iRU%2BWumAV7BTIn4Turd3BGopyaDpPeht41YDMm0%3D&st=2021-04-10T00%3A38%3A52Z&se=2021-05-11T00%3A43%3A52Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/57856ef7-e8cf-54ca-0d12-df5f42d1e8bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-10 00:44 UTC, alison-mk commented
Thanks for the review, @mscharlock! Ready for you to take another look when you have a chance.

2021-04-12 17:50 UTC, mscharlock approved these changes

2021-04-12 19:09 UTC, merged