[Excel] (ribbon) open task panes from contextual tabs
OfficeDev/office-js-docs-pr pull request #2803
Opened 2021-07-09 00:32 UTC by Rick-Kirkham

2021-07-09 00:33 UTC, opbld34 commented
Docs Build status updates of commit _[ef65f91](https://github.com/OfficeDev/office-js-docs-pr/commits/ef65f9110b183cdacc8c77dae31e6aecfa366ffe)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/design/contextual-tabs.md](https://github.com/OfficeDev/office-js-docs-pr/blob/contextual-tabs-2-taskpanes/docs/design/contextual-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/design/contextual-tabs?branch=pr-en-us-2803) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C9%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C202107090032194497-2803%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-08T09%3A59%3A11Z&ske=2021-07-15T10%3A04%3A11Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-09T00%3A27%3A59Z&se=2021-08-09T00%3A32%3A59Z&sr=b&sp=r&sig=JWBYH5XmtS8pEmoIHo%2B4Ges8RcctonlYrYt%2F0PNiVA8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/57856ef7-e8cf-54ca-0d12-df5f42d1e8bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-09 01:03 UTC, lindalu-MSFT requested changes
I didn't address the "you cans" in this topic, but there are 10 instances. Suggest you reduce the number of times you use this phrase. For example, in the introductory paragraph:

"You can include custom contextual tabs in your Office Add-in and specify when they are visible or hidden, by creating event handlers that change the visibility."

can be:

"Include custom contextual tabs in your Office Add-in and specify when they are visible or hidden, by creating event handlers that change the visibility."

2021-07-09 01:03 UTC, lindalu-MSFT commented on docs/design/contextual-tabs.md
>  ## Localizing the JSON blob
```suggestion
## Localize the JSON blob
```
I checked the article, and this is the only heading that uses a gerund verb. Suggest changing to align with other headings in the topic.

2021-07-09 18:31 UTC, opbld33 commented
Docs Build status updates of commit _[70d803d](https://github.com/OfficeDev/office-js-docs-pr/commits/70d803dfb8de118753a11251284b67bc2f67a186)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/design/contextual-tabs.md](https://github.com/OfficeDev/office-js-docs-pr/blob/contextual-tabs-2-taskpanes/docs/design/contextual-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/design/contextual-tabs?branch=pr-en-us-2803) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C9%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C202107091830271404-2803%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-06T07%3A03%3A42Z&ske=2021-07-13T07%3A08%3A42Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-09T18%3A26%3A06Z&se=2021-08-09T18%3A31%3A06Z&sr=b&sp=r&sig=Bk9B7RB4q2PTFj0K7OqQbbcteOPSK%2FHHvqoghODIbW0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/57856ef7-e8cf-54ca-0d12-df5f42d1e8bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-09 18:41 UTC, opbld30 commented
Docs Build status updates of commit _[dc2dac8](https://github.com/OfficeDev/office-js-docs-pr/commits/dc2dac8a44aa23e7f2936e2f8e751996f8f44234)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/design/contextual-tabs.md](https://github.com/OfficeDev/office-js-docs-pr/blob/contextual-tabs-2-taskpanes/docs/design/contextual-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/design/contextual-tabs?branch=pr-en-us-2803) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C9%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C202107091840561118-2803%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-06T07%3A03%3A42Z&ske=2021-07-13T07%3A08%3A42Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-09T18%3A36%3A33Z&se=2021-08-09T18%3A41%3A33Z&sr=b&sp=r&sig=yVsy3JIAlQ3FV9k11groB0tB6GZEq%2FgBRa1mNQr6e8Y%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/57856ef7-e8cf-54ca-0d12-df5f42d1e8bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-09 18:44 UTC, Rick-Kirkham commented
> I didn't address the "you cans" in this topic, but there are 10 instances. Suggest you reduce the number of times you use this phrase. For example, in the introductory paragraph:
> 
> "You can include custom contextual tabs in your Office Add-in and specify when they are visible or hidden, by creating event handlers that change the visibility."
> 
> can be:
> 
> "Include custom contextual tabs in your Office Add-in and specify when they are visible or hidden, by creating event handlers that change the visibility."

I've fixed this in places where it can be. In some places, the "you can" is appropriate because it expresses an option, not something the reader must do.

2021-07-12 18:13 UTC, lindalu-MSFT commented
@Rick-Kirkham That's a great way to differentiate. If it's an option, then "you can" is fine. If not, try to write the sentence differently to avoid "you can."

2021-07-14 21:24 UTC, davidchesnut requested changes
Looking good. A few suggestions. Thanks!

2021-07-14 21:24 UTC, davidchesnut commented on docs/design/contextual-tabs.md
> +In a task pane, to open a page that is at a different URL from the URL of the shared runtime, specify a `sourceLocation` property in the definition of the action. In the following example, a second t
```suggestion
To open any task pane that is not the default task pane, specify a `sourceLocation` property in the definition of the action. In the following example, a second task pane is opened from a different button.
```

2021-07-14 21:24 UTC, davidchesnut commented on docs/design/contextual-tabs.md
> +
You should also document the `title` and `supportPinning` properties for opening a task pane.
```json
  {
            "id": "showTaskpaneContoso",
            "type": "ShowTaskpane",
            "title": "Contoso task pane",
            "supportPinning": false
          }
```

2021-07-14 21:24 UTC, davidchesnut commented on docs/design/contextual-tabs.md
> +## Localize the JSON blob
I think this meant to say JSON. Not a binary large object (BLOB).
```suggestion
## Localize the JSON text
```

2021-07-14 21:24 UTC, davidchesnut commented on docs/design/contextual-tabs.md
> +> - When a `sourceLocation` is specified for the action, then the task pane does *not* use the shared runtime.
```suggestion
> - When a `sourceLocation` is specified for the action, then the task pane does *not* use the shared runtime. It runs in a new JavaScript runtime.
```

2021-07-15 17:55 UTC, opbld32 commented
Docs Build status updates of commit _[e5b1f2b](https://github.com/OfficeDev/office-js-docs-pr/commits/e5b1f2bcfac63d63bdb56cae89443685564be5da)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/design/contextual-tabs.md](https://github.com/OfficeDev/office-js-docs-pr/blob/contextual-tabs-2-taskpanes/docs/design/contextual-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/design/contextual-tabs?branch=pr-en-us-2803) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C15%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C202107151755136354-2803%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-14T21%3A54%3A41Z&ske=2021-07-21T21%3A59%3A41Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-15T17%3A50%3A55Z&se=2021-08-15T17%3A55%3A55Z&sr=b&sp=r&sig=dy1wuHMiltmZiTMGScIK0DqqVJ%2FcfixoFJEFUUlxH7Q%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/57856ef7-e8cf-54ca-0d12-df5f42d1e8bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-15 18:05 UTC, opbld31 commented
Docs Build status updates of commit _[886b88d](https://github.com/OfficeDev/office-js-docs-pr/commits/886b88d14782d3dd5899c6911d34873a47a714e5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/design/contextual-tabs.md](https://github.com/OfficeDev/office-js-docs-pr/blob/contextual-tabs-2-taskpanes/docs/design/contextual-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/design/contextual-tabs?branch=pr-en-us-2803) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C15%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C202107151804308887-2803%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-13T08%3A32%3A34Z&ske=2021-07-20T08%3A37%3A34Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-15T18%3A00%3A09Z&se=2021-08-15T18%3A05%3A09Z&sr=b&sp=r&sig=HfX5gnOm%2FLaHbHJz7GfTxUrZ0llwpdnbmEmwK%2FNy91Q%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/57856ef7-e8cf-54ca-0d12-df5f42d1e8bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-07-15 22:03 UTC, merged