[troubleshooting] (Cache) Suggest cache clearing as an overarching strategy
OfficeDev/office-js-docs-pr pull request #2867
Opened 2021-08-09 22:13 UTC by AlexJerabek

Fixes #2297.

2021-08-09 22:14 UTC, opbld34 commented
Docs Build status updates of commit _[517fed8](https://github.com/OfficeDev/office-js-docs-pr/commits/517fed829279114cd9a36f0d32462209a672a0af)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/testing/clear-cache.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-Cache/docs/testing/clear-cache.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/testing/clear-cache?branch=pr-en-us-2867) |
[docs/testing/troubleshoot-development-errors.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-Cache/docs/testing/troubleshoot-development-errors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/testing/troubleshoot-development-errors?branch=pr-en-us-2867) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C9%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C202108092213364109-2867%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=IlYpVALRsc6xh4QYABEX2E0jNtDwj3zQLyHqt9vY5uE%3D&st=2021-08-09T22%3A09%3A19Z&se=2021-09-09T22%3A14%3A19Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/57856ef7-e8cf-54ca-0d12-df5f42d1e8bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-09 22:30 UTC, davidchesnut requested changes
Looks like the **Changes to add-in commands including ribbon buttons and menu items do not take effect** section was accidentally deleted. Can you add it back in?

2021-08-09 22:30 UTC, davidchesnut commented on docs/testing/troubleshoot-development-errors.md
> +Here is a list of common issues you may encounter while developing an Office Add-in. For further help with your specific scenario, please post your questions to [Stack Overflow](https://stackoverflow
```suggestion
Here is a list of common issues you may encounter while developing an Office Add-in. For further help with your specific scenario, please post your questions to [Microsoft Q&A](https://docs.microsoft.com/answers/topics/office-js-dev.html) using the office-js-dev tag.
```

I recommend moving this to bottom of article as more of a "if all else fails reach out here" rather than encourage going straight to Q&A before looking at the troubleshooting that might help.

2021-08-09 22:30 UTC, davidchesnut commented on docs/testing/troubleshoot-development-errors.md
> +> Clearing the Office cache often fixes issues related to stale code. This guarantees the latest manifest is uploaded, bringing the most recent file names, menu text, and other command elements. To l
```suggestion
> Clearing the Office cache often fixes issues related to stale code. This guarantees the latest manifest is uploaded, using the current file names, menu text, and other command elements. To learn more, see [Clear the Office cache](clear-cache.md).
```

2021-08-09 22:35 UTC, opbld31 commented
Docs Build status updates of commit _[a9ea75f](https://github.com/OfficeDev/office-js-docs-pr/commits/a9ea75fca68062a3c3c0c0ce7a3a4e063cec8d6b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/testing/troubleshoot-development-errors.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-Cache/docs/testing/troubleshoot-development-errors.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/testing/troubleshoot-development-errors?branch=pr-en-us-2867) | [Details](#user-content-51934c881a87659c181f49f46eee5bac-3ad3c2f1)
[docs/testing/clear-cache.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-Cache/docs/testing/clear-cache.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/testing/clear-cache?branch=pr-en-us-2867) |

<a id="51934c881a87659c181f49f46eee5bac-3ad3c2f1"></a>
### [docs/testing/troubleshoot-development-errors.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-Cache/docs/testing/troubleshoot-development-errors.md)
 - **Line 10, Column 162**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/answers/topics/office-js-dev.html' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C9%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C202108092234481212-2867%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=OgDXbHUTPTxJSKEz099%2FgofcCvMSPLxN2txPfY4aEvM%3D&st=2021-08-09T22%3A30%3A32Z&se=2021-09-09T22%3A35%3A32Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/57856ef7-e8cf-54ca-0d12-df5f42d1e8bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-09 22:36 UTC, AlexJerabek commented
@davidchesnut I had intentionally removed the **Changes to add-in commands including ribbon buttons and menu items do not take effect** section since it was just the cache clearing instructions. Made more sense with the Tip at the top. I can add the header back, link to the cache clearing doc, and move the tip to the end.

2021-08-09 22:44 UTC, opbld30 commented
Docs Build status updates of commit _[d787f30](https://github.com/OfficeDev/office-js-docs-pr/commits/d787f303448dfb04b2aa36f22eb1947fb45e33c9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/testing/clear-cache.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-Cache/docs/testing/clear-cache.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/testing/clear-cache?branch=pr-en-us-2867) |
[docs/testing/troubleshoot-development-errors.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-Cache/docs/testing/troubleshoot-development-errors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/testing/troubleshoot-development-errors?branch=pr-en-us-2867) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C9%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C202108092244029174-2867%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=Hyfn80%2B0at8beAgUFdg%2B3mZ6oWmv9%2Fgm7dEEAdOj0z0%3D&st=2021-08-09T22%3A39%3A40Z&se=2021-09-09T22%3A44%3A40Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/57856ef7-e8cf-54ca-0d12-df5f42d1e8bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-09 22:49 UTC, opbld32 commented
Docs Build status updates of commit _[f29548a](https://github.com/OfficeDev/office-js-docs-pr/commits/f29548ae88075ed5b9d9459699b189cceb46b4f2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/testing/clear-cache.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-Cache/docs/testing/clear-cache.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/testing/clear-cache?branch=pr-en-us-2867) |
[docs/testing/troubleshoot-development-errors.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-Cache/docs/testing/troubleshoot-development-errors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/testing/troubleshoot-development-errors?branch=pr-en-us-2867) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C9%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C202108092248378458-2867%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=n%2ByWWoa6bV3DRwn8mMLuFuRlPZtFcNIKzo%2F%2Fx1mZfYo%3D&st=2021-08-09T22%3A44%3A22Z&se=2021-09-09T22%3A49%3A22Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/57856ef7-e8cf-54ca-0d12-df5f42d1e8bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-03 20:52 UTC, davidchesnut approved these changes

2021-09-03 20:56 UTC, opbld30 commented
Docs Build status updates of commit _[359b0ba](https://github.com/OfficeDev/office-js-docs-pr/commits/359b0bad19c73b1995ee7f7ebf18df639298fa7b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/testing/clear-cache.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-Cache/docs/testing/clear-cache.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/testing/clear-cache?branch=pr-en-us-2867) |
[docs/testing/troubleshoot-development-errors.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-Cache/docs/testing/troubleshoot-development-errors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/testing/troubleshoot-development-errors?branch=pr-en-us-2867) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C3%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C202109032055557046-2867%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=Gnf1s5JwDnF7STIJV07NKsCM9Wv5Tl7%2F2W1g2fatg%2F8%3D&st=2021-09-03T20%3A51%3A39Z&se=2021-10-04T20%3A56%3A39Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/57856ef7-e8cf-54ca-0d12-df5f42d1e8bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-03 20:56 UTC, merged