[Excel] (Charts) Add chart data table article section
OfficeDev/office-js-docs-pr pull request #3103
Opened 2021-11-24 03:11 UTC by alison-mk

2021-11-24 03:12 UTC, opbld34 commented
Docs Build status updates of commit _[e4e8671](https://github.com/OfficeDev/office-js-docs-pr/commits/e4e8671957d83a238d54fedc324fcb034883a1e6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/excel/excel-add-ins-charts.md](https://github.com/OfficeDev/office-js-docs-pr/blob/alison-mk-chart-data-table/docs/excel/excel-add-ins-charts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-charts?branch=pr-en-us-3103) |
[docs/images/excel-charts-data-table.png](https://github.com/OfficeDev/office-js-docs-pr/blob/alison-mk-chart-data-table/docs/images/excel-charts-data-table.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-charts?branch=pr-en-us-3103) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C24%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C202111240311227750-3103%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-25T03%3A11%3A59Z&sr=b&sp=r&sig=kKjkaA44r7swwvOvmQQjC2n1TXG9ZMfpFVICMQRfPn8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/57856ef7-e8cf-54ca-0d12-df5f42d1e8bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-24 03:23 UTC, opbld34 commented
Docs Build status updates of commit _[14d8c94](https://github.com/OfficeDev/office-js-docs-pr/commits/14d8c944601dfa66f44236dff87ac17cb903ff03)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/excel/excel-add-ins-charts.md](https://github.com/OfficeDev/office-js-docs-pr/blob/alison-mk-chart-data-table/docs/excel/excel-add-ins-charts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-charts?branch=pr-en-us-3103) |
[docs/images/excel-charts-data-table.png](https://github.com/OfficeDev/office-js-docs-pr/blob/alison-mk-chart-data-table/docs/images/excel-charts-data-table.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-charts?branch=pr-en-us-3103) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C24%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C202111240322383848-3103%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-25T03%3A23%3A12Z&sr=b&sp=r&sig=tTnzrVkqhHPECcb0cuo4Dfr1n0ukBA8YH%2FXuxR%2BOcC4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/57856ef7-e8cf-54ca-0d12-df5f42d1e8bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-29 18:02 UTC, AlexJerabek requested changes
The section looks good. My only real concern for re-review is the about the image.

2021-11-29 18:02 UTC, AlexJerabek commented on docs/excel/excel-add-ins-charts.md
> +The following screenshot shows the data table that the preceding code sample creates, including the custom formatting of the data table.
The clause about formatting the data table seems redundant.
```suggestion
The following screenshot shows the data table that the preceding code sample creates.
```

2021-11-29 20:59 UTC, opbld33 commented
Docs Build status updates of commit _[1664617](https://github.com/OfficeDev/office-js-docs-pr/commits/1664617e7fbab07a4389c9ae13f2e1716e74a7eb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/excel/excel-add-ins-charts.md](https://github.com/OfficeDev/office-js-docs-pr/blob/alison-mk-chart-data-table/docs/excel/excel-add-ins-charts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-charts?branch=pr-en-us-3103) |
[docs/images/excel-charts-data-table.png](https://github.com/OfficeDev/office-js-docs-pr/blob/alison-mk-chart-data-table/docs/images/excel-charts-data-table.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-charts?branch=pr-en-us-3103) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C29%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C202111292058417364-3103%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-30T20%3A59%3A23Z&sr=b&sp=r&sig=vG%2BItE4FYEMgZUpzUvZwzUmhAaTIv0EXfuMiTHm4moU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/57856ef7-e8cf-54ca-0d12-df5f42d1e8bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-29 21:01 UTC, alison-mk commented on docs/excel/excel-add-ins-charts.md
> +![A chart with a data table, showcasing custom formatting of the data table.](../images/excel-charts-data-table.png)
Good catch! Will fix.

2021-11-29 21:27 UTC, alison-mk commented on docs/excel/excel-add-ins-charts.md
> +You can access the data table element of a chart with the [`Chart.getDataTableOrNullObject`](/javascript/api/excel/excel.chart#getDataTableOrNullObject__) method. This method returns the [`ChartDataT
I had the same thought and experience.

2021-11-29 21:30 UTC, opbld32 commented
Docs Build status updates of commit _[75d5654](https://github.com/OfficeDev/office-js-docs-pr/commits/75d5654709bb06844063916d9d331711715eb562)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/excel/excel-add-ins-charts.md](https://github.com/OfficeDev/office-js-docs-pr/blob/alison-mk-chart-data-table/docs/excel/excel-add-ins-charts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-charts?branch=pr-en-us-3103) |
[docs/images/excel-charts-data-table.png](https://github.com/OfficeDev/office-js-docs-pr/blob/alison-mk-chart-data-table/docs/images/excel-charts-data-table.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-charts?branch=pr-en-us-3103) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C29%5C57856ef7-e8cf-54ca-0d12-df5f42d1e8bb%5CPullRequest%5C202111292130143295-3103%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-30T21%3A30%3A52Z&sr=b&sp=r&sig=h86XEbw3WD%2BJBL07TsDwnyUartXgLhGuTiKSZibm27Q%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/57856ef7-e8cf-54ca-0d12-df5f42d1e8bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-29 22:46 UTC, AlexJerabek approved these changes

2021-11-30 00:59 UTC, merged