[admin] (Links) Updating reference anchor links
OfficeDev/office-js-docs-pr pull request #3213
Opened 2022-02-01 19:28 UTC by AlexJerabek

[Staging site link](https://review.docs.microsoft.com/en-us/office/dev/add-ins/overview/office-add-ins?branch=AlexJ-ReferenceLinks)

This PR updates the links to our reference documentation to use the new link anchor format.

2022-02-01 19:29 UTC, opbld33 commented
Docs Build status updates of commit _[d531e64](https://github.com/OfficeDev/office-js-docs-pr/commits/d531e649b9fc52f4543f2459375737045cd8a497)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/concepts/add-in-development-best-practices.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/concepts/add-in-development-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/concepts/add-in-development-best-practices?branch=pr-en-us-3213) |
[docs/concepts/resource-limits-and-performance-optimization.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/concepts/resource-limits-and-performance-optimization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/concepts/resource-limits-and-performance-optimization?branch=pr-en-us-3213) |
[docs/design/contextual-tabs.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/design/contextual-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/design/contextual-tabs?branch=pr-en-us-3213) |
[docs/design/disable-add-in-commands.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/design/disable-add-in-commands.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/design/disable-add-in-commands?branch=pr-en-us-3213) |
[docs/design/keyboard-shortcuts.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/design/keyboard-shortcuts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/design/keyboard-shortcuts?branch=pr-en-us-3213) |
[docs/develop/add-in-manifests.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/add-in-manifests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/add-in-manifests?branch=pr-en-us-3213) |
[docs/develop/application-specific-api-model.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/application-specific-api-model.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/application-specific-api-model?branch=pr-en-us-3213) |
[docs/develop/asynchronous-programming-in-office-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/asynchronous-programming-in-office-add-ins.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/asynchronous-programming-in-office-add-ins?branch=pr-en-us-3213) |
[docs/develop/auth-with-office-dialog-api.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/auth-with-office-dialog-api.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/auth-with-office-dialog-api?branch=pr-en-us-3213) |
[docs/develop/develop-office-add-ins-for-the-ipad.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/develop-office-add-ins-for-the-ipad.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/develop-office-add-ins-for-the-ipad?branch=pr-en-us-3213) |
[docs/develop/dialog-api-in-office-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/dialog-api-in-office-add-ins.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/dialog-api-in-office-add-ins?branch=pr-en-us-3213) |
[docs/develop/dialog-best-practices.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/dialog-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/dialog-best-practices?branch=pr-en-us-3213) |
[docs/develop/office-javascript-api-object-model.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/office-javascript-api-object-model.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/office-javascript-api-object-model?branch=pr-en-us-3213) |
[docs/develop/persisting-add-in-state-and-settings.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/persisting-add-in-state-and-settings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/persisting-add-in-state-and-settings?branch=pr-en-us-3213) |
[docs/develop/read-and-write-data-to-the-active-selection-in-a-document-or-spreadsheet.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/read-and-write-data-to-the-active-selection-in-a-document-or-spreadsheet.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/read-and-write-data-to-the-active-selection-in-a-document-or-spreadsheet?branch=pr-en-us-3213) |
[docs/develop/requesting-permissions-for-api-use-in-content-and-task-pane-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/requesting-permissions-for-api-use-in-content-and-task-pane-add-ins.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/requesting-permissions-for-api-use-in-content-and-task-pane-add-ins?branch=pr-en-us-3213) |
[docs/develop/show-hide-add-in.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/show-hide-add-in.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/show-hide-add-in?branch=pr-en-us-3213) |
[docs/develop/specify-office-hosts-and-api-requirements.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/specify-office-hosts-and-api-requirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/specify-office-hosts-and-api-requirements?branch=pr-en-us-3213) |
[docs/develop/support-for-task-pane-and-content-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/support-for-task-pane-and-content-add-ins.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/support-for-task-pane-and-content-add-ins?branch=pr-en-us-3213) |
[docs/excel/call-excel-apis-from-custom-function.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/excel/call-excel-apis-from-custom-function.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/call-excel-apis-from-custom-function?branch=pr-en-us-3213) |
[docs/excel/co-authoring-in-excel-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/excel/co-authoring-in-excel-add-ins.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/co-authoring-in-excel-add-ins?branch=pr-en-us-3213) |
[docs/excel/excel-add-ins-charts.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/excel/excel-add-ins-charts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-charts?branch=pr-en-us-3213) |
[docs/excel/excel-add-ins-data-validation.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/excel/excel-add-ins-data-validation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/exce [...]

2022-02-01 19:55 UTC, opbld31 commented
Docs Build status updates of commit _[eea4f4d](https://github.com/OfficeDev/office-js-docs-pr/commits/eea4f4d951224c65664605e55b0c0f95eedcdce4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/concepts/add-in-development-best-practices.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/concepts/add-in-development-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/concepts/add-in-development-best-practices?branch=pr-en-us-3213) |
[docs/concepts/resource-limits-and-performance-optimization.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/concepts/resource-limits-and-performance-optimization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/concepts/resource-limits-and-performance-optimization?branch=pr-en-us-3213) |
[docs/design/contextual-tabs.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/design/contextual-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/design/contextual-tabs?branch=pr-en-us-3213) |
[docs/design/disable-add-in-commands.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/design/disable-add-in-commands.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/design/disable-add-in-commands?branch=pr-en-us-3213) |
[docs/design/keyboard-shortcuts.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/design/keyboard-shortcuts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/design/keyboard-shortcuts?branch=pr-en-us-3213) |
[docs/develop/add-in-manifests.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/add-in-manifests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/add-in-manifests?branch=pr-en-us-3213) |
[docs/develop/application-specific-api-model.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/application-specific-api-model.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/application-specific-api-model?branch=pr-en-us-3213) |
[docs/develop/asynchronous-programming-in-office-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/asynchronous-programming-in-office-add-ins.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/asynchronous-programming-in-office-add-ins?branch=pr-en-us-3213) |
[docs/develop/auth-with-office-dialog-api.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/auth-with-office-dialog-api.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/auth-with-office-dialog-api?branch=pr-en-us-3213) |
[docs/develop/develop-office-add-ins-for-the-ipad.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/develop-office-add-ins-for-the-ipad.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/develop-office-add-ins-for-the-ipad?branch=pr-en-us-3213) |
[docs/develop/dialog-api-in-office-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/dialog-api-in-office-add-ins.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/dialog-api-in-office-add-ins?branch=pr-en-us-3213) |
[docs/develop/dialog-best-practices.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/dialog-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/dialog-best-practices?branch=pr-en-us-3213) |
[docs/develop/office-javascript-api-object-model.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/office-javascript-api-object-model.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/office-javascript-api-object-model?branch=pr-en-us-3213) |
[docs/develop/persisting-add-in-state-and-settings.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/persisting-add-in-state-and-settings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/persisting-add-in-state-and-settings?branch=pr-en-us-3213) |
[docs/develop/read-and-write-data-to-the-active-selection-in-a-document-or-spreadsheet.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/read-and-write-data-to-the-active-selection-in-a-document-or-spreadsheet.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/read-and-write-data-to-the-active-selection-in-a-document-or-spreadsheet?branch=pr-en-us-3213) |
[docs/develop/requesting-permissions-for-api-use-in-content-and-task-pane-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/requesting-permissions-for-api-use-in-content-and-task-pane-add-ins.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/requesting-permissions-for-api-use-in-content-and-task-pane-add-ins?branch=pr-en-us-3213) |
[docs/develop/show-hide-add-in.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/show-hide-add-in.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/show-hide-add-in?branch=pr-en-us-3213) |
[docs/develop/specify-office-hosts-and-api-requirements.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/specify-office-hosts-and-api-requirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/specify-office-hosts-and-api-requirements?branch=pr-en-us-3213) |
[docs/develop/support-for-task-pane-and-content-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/support-for-task-pane-and-content-add-ins.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/support-for-task-pane-and-content-add-ins?branch=pr-en-us-3213) |
[docs/excel/call-excel-apis-from-custom-function.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/excel/call-excel-apis-from-custom-function.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/call-excel-apis-from-custom-function?branch=pr-en-us-3213) |
[docs/excel/co-authoring-in-excel-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/excel/co-authoring-in-excel-add-ins.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/co-authoring-in-excel-add-ins?branch=pr-en-us-3213) |
[docs/excel/excel-add-ins-charts.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/excel/excel-add-ins-charts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-charts?branch=pr-en-us-3213) |
[docs/excel/excel-add-ins-data-validation.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/excel/excel-add-ins-data-validation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/exce [...]

2022-02-01 19:57 UTC, opbld32 commented
Docs Build status updates of commit _[eea4f4d](https://github.com/OfficeDev/office-js-docs-pr/commits/eea4f4d951224c65664605e55b0c0f95eedcdce4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/concepts/add-in-development-best-practices.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/concepts/add-in-development-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/concepts/add-in-development-best-practices?branch=pr-en-us-3213) |
[docs/concepts/resource-limits-and-performance-optimization.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/concepts/resource-limits-and-performance-optimization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/concepts/resource-limits-and-performance-optimization?branch=pr-en-us-3213) |
[docs/design/contextual-tabs.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/design/contextual-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/design/contextual-tabs?branch=pr-en-us-3213) |
[docs/design/disable-add-in-commands.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/design/disable-add-in-commands.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/design/disable-add-in-commands?branch=pr-en-us-3213) |
[docs/design/keyboard-shortcuts.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/design/keyboard-shortcuts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/design/keyboard-shortcuts?branch=pr-en-us-3213) |
[docs/develop/add-in-manifests.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/add-in-manifests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/add-in-manifests?branch=pr-en-us-3213) |
[docs/develop/application-specific-api-model.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/application-specific-api-model.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/application-specific-api-model?branch=pr-en-us-3213) |
[docs/develop/asynchronous-programming-in-office-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/asynchronous-programming-in-office-add-ins.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/asynchronous-programming-in-office-add-ins?branch=pr-en-us-3213) |
[docs/develop/auth-with-office-dialog-api.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/auth-with-office-dialog-api.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/auth-with-office-dialog-api?branch=pr-en-us-3213) |
[docs/develop/develop-office-add-ins-for-the-ipad.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/develop-office-add-ins-for-the-ipad.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/develop-office-add-ins-for-the-ipad?branch=pr-en-us-3213) |
[docs/develop/dialog-api-in-office-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/dialog-api-in-office-add-ins.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/dialog-api-in-office-add-ins?branch=pr-en-us-3213) |
[docs/develop/dialog-best-practices.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/dialog-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/dialog-best-practices?branch=pr-en-us-3213) |
[docs/develop/office-javascript-api-object-model.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/office-javascript-api-object-model.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/office-javascript-api-object-model?branch=pr-en-us-3213) |
[docs/develop/persisting-add-in-state-and-settings.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/persisting-add-in-state-and-settings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/persisting-add-in-state-and-settings?branch=pr-en-us-3213) |
[docs/develop/read-and-write-data-to-the-active-selection-in-a-document-or-spreadsheet.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/read-and-write-data-to-the-active-selection-in-a-document-or-spreadsheet.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/read-and-write-data-to-the-active-selection-in-a-document-or-spreadsheet?branch=pr-en-us-3213) |
[docs/develop/requesting-permissions-for-api-use-in-content-and-task-pane-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/requesting-permissions-for-api-use-in-content-and-task-pane-add-ins.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/requesting-permissions-for-api-use-in-content-and-task-pane-add-ins?branch=pr-en-us-3213) |
[docs/develop/show-hide-add-in.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/show-hide-add-in.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/show-hide-add-in?branch=pr-en-us-3213) |
[docs/develop/specify-office-hosts-and-api-requirements.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/specify-office-hosts-and-api-requirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/specify-office-hosts-and-api-requirements?branch=pr-en-us-3213) |
[docs/develop/support-for-task-pane-and-content-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/support-for-task-pane-and-content-add-ins.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/support-for-task-pane-and-content-add-ins?branch=pr-en-us-3213) |
[docs/excel/call-excel-apis-from-custom-function.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/excel/call-excel-apis-from-custom-function.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/call-excel-apis-from-custom-function?branch=pr-en-us-3213) |
[docs/excel/co-authoring-in-excel-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/excel/co-authoring-in-excel-add-ins.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/co-authoring-in-excel-add-ins?branch=pr-en-us-3213) |
[docs/excel/excel-add-ins-charts.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/excel/excel-add-ins-charts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-charts?branch=pr-en-us-3213) |
[docs/excel/excel-add-ins-data-validation.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/excel/excel-add-ins-data-validation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/exce [...]

2022-02-01 21:33 UTC, opbld30 commented
Docs Build status updates of commit _[dacd04a](https://github.com/OfficeDev/office-js-docs-pr/commits/dacd04a66fb178e8b30ee620e07fb660a01200db)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/concepts/add-in-development-best-practices.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/concepts/add-in-development-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/concepts/add-in-development-best-practices?branch=pr-en-us-3213) |
[docs/concepts/resource-limits-and-performance-optimization.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/concepts/resource-limits-and-performance-optimization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/concepts/resource-limits-and-performance-optimization?branch=pr-en-us-3213) |
[docs/design/contextual-tabs.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/design/contextual-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/design/contextual-tabs?branch=pr-en-us-3213) |
[docs/design/disable-add-in-commands.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/design/disable-add-in-commands.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/design/disable-add-in-commands?branch=pr-en-us-3213) |
[docs/design/keyboard-shortcuts.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/design/keyboard-shortcuts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/design/keyboard-shortcuts?branch=pr-en-us-3213) |
[docs/develop/add-in-manifests.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/add-in-manifests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/add-in-manifests?branch=pr-en-us-3213) |
[docs/develop/application-specific-api-model.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/application-specific-api-model.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/application-specific-api-model?branch=pr-en-us-3213) |
[docs/develop/asynchronous-programming-in-office-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/asynchronous-programming-in-office-add-ins.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/asynchronous-programming-in-office-add-ins?branch=pr-en-us-3213) |
[docs/develop/auth-with-office-dialog-api.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/auth-with-office-dialog-api.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/auth-with-office-dialog-api?branch=pr-en-us-3213) |
[docs/develop/authorize-to-microsoft-graph.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/authorize-to-microsoft-graph.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/authorize-to-microsoft-graph?branch=pr-en-us-3213) |
[docs/develop/develop-office-add-ins-for-the-ipad.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/develop-office-add-ins-for-the-ipad.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/develop-office-add-ins-for-the-ipad?branch=pr-en-us-3213) |
[docs/develop/dialog-api-in-office-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/dialog-api-in-office-add-ins.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/dialog-api-in-office-add-ins?branch=pr-en-us-3213) |
[docs/develop/dialog-best-practices.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/dialog-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/dialog-best-practices?branch=pr-en-us-3213) |
[docs/develop/office-javascript-api-object-model.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/office-javascript-api-object-model.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/office-javascript-api-object-model?branch=pr-en-us-3213) |
[docs/develop/overview-authn-authz.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/overview-authn-authz.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/overview-authn-authz?branch=pr-en-us-3213) |
[docs/develop/persisting-add-in-state-and-settings.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/persisting-add-in-state-and-settings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/persisting-add-in-state-and-settings?branch=pr-en-us-3213) |
[docs/develop/read-and-write-data-to-the-active-selection-in-a-document-or-spreadsheet.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/read-and-write-data-to-the-active-selection-in-a-document-or-spreadsheet.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/read-and-write-data-to-the-active-selection-in-a-document-or-spreadsheet?branch=pr-en-us-3213) |
[docs/develop/requesting-permissions-for-api-use-in-content-and-task-pane-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/requesting-permissions-for-api-use-in-content-and-task-pane-add-ins.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/requesting-permissions-for-api-use-in-content-and-task-pane-add-ins?branch=pr-en-us-3213) |
[docs/develop/show-hide-add-in.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/show-hide-add-in.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/show-hide-add-in?branch=pr-en-us-3213) |
[docs/develop/specify-office-hosts-and-api-requirements.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/specify-office-hosts-and-api-requirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/specify-office-hosts-and-api-requirements?branch=pr-en-us-3213) |
[docs/develop/sso-in-office-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/sso-in-office-add-ins.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/sso-in-office-add-ins?branch=pr-en-us-3213) |
[docs/develop/support-for-task-pane-and-content-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/support-for-task-pane-and-content-add-ins.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/support-for-task-pane-and-content-add-ins?branch=pr-en-us-3213) |
[docs/develop/troubleshoot-sso-in-office-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/troubleshoot-sso-in-office-add-ins.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/troubleshoot-sso-i [...]

2022-02-02 02:06 UTC, ElizabethSamuel-MSFT requested changes
Found a few missed ones. Also took the opportunity to include some minor cleanup.

2022-02-02 02:06 UTC, ElizabethSamuel-MSFT commented on docs/reference/objectmodel/requirement-set-1.2/office.context.mailbox.md
> +| [getCallbackTokenAsync(callback, [userContext])](/javascript/api/outlook/office.mailbox?view=outlook-js-1.2&preserve-view=true#outlook-office-mailbox-getcallbacktokenasync-member(1)) | ReadItem | C
```suggestion
| [getCallbackTokenAsync(callback, [userContext])](/javascript/api/outlook/office.mailbox?view=outlook-js-1.2&preserve-view=true#outlook-office-mailbox-getcallbacktokenasync-member(1)) | ReadItem | Read | [1.1](../requirement-set-1.1/outlook-requirement-set-1.1.md) |
```

2022-02-02 02:06 UTC, ElizabethSamuel-MSFT commented on docs/reference/objectmodel/requirement-set-1.5/office.context.mailbox.md
> +| [getCallbackTokenAsync(callback, [userContext])](/javascript/api/outlook/office.mailbox?view=outlook-js-1.5&preserve-view=true#outlook-office-mailbox-getcallbacktokenasync-member(1)) | ReadItem | C
```suggestion
| [getCallbackTokenAsync(callback, [userContext])](/javascript/api/outlook/office.mailbox?view=outlook-js-1.5&preserve-view=true#outlook-office-mailbox-getcallbacktokenasync-member(2)) | ReadItem | Compose<br>Read | [1.3](../requirement-set-1.3/outlook-requirement-set-1.3.md)<br>[1.1](../requirement-set-1.1/outlook-requirement-set-1.1.md) |
```

2022-02-02 02:06 UTC, ElizabethSamuel-MSFT commented on docs/reference/objectmodel/requirement-set-1.6/office.context.mailbox.md
> +| [getCallbackTokenAsync(callback, [userContext])](/javascript/api/outlook/office.mailbox?view=outlook-js-1.6&preserve-view=true#outlook-office-mailbox-getcallbacktokenasync-member(1)) | ReadItem | C
```suggestion
| [getCallbackTokenAsync(callback, [userContext])](/javascript/api/outlook/office.mailbox?view=outlook-js-1.6&preserve-view=true#outlook-office-mailbox-getcallbacktokenasync-member(2)) | ReadItem | Compose<br>Read | [1.3](../requirement-set-1.3/outlook-requirement-set-1.3.md)<br>[1.1](../requirement-set-1.1/outlook-requirement-set-1.1.md) |
```

2022-02-02 02:06 UTC, ElizabethSamuel-MSFT commented on docs/reference/objectmodel/requirement-set-1.7/office.context.mailbox.md
> +| [getCallbackTokenAsync(callback, [userContext])](/javascript/api/outlook/office.mailbox?view=outlook-js-1.7&preserve-view=true#outlook-office-mailbox-getcallbacktokenasync-member(1)) | ReadItem | C
```suggestion
| [getCallbackTokenAsync(callback, [userContext])](/javascript/api/outlook/office.mailbox?view=outlook-js-1.7&preserve-view=true#outlook-office-mailbox-getcallbacktokenasync-member(2)) | ReadItem | Compose<br>Read | [1.3](../requirement-set-1.3/outlook-requirement-set-1.3.md)<br>[1.1](../requirement-set-1.1/outlook-requirement-set-1.1.md) |
```

2022-02-02 02:06 UTC, ElizabethSamuel-MSFT commented on docs/reference/objectmodel/requirement-set-1.8/office.context.mailbox.md
> +| [getCallbackTokenAsync(callback, [userContext])](/javascript/api/outlook/office.mailbox?view=outlook-js-1.8&preserve-view=true#outlook-office-mailbox-getcallbacktokenasync-member(1)) | ReadItem | C
```suggestion
| [getCallbackTokenAsync(callback, [userContext])](/javascript/api/outlook/office.mailbox?view=outlook-js-1.8&preserve-view=true#outlook-office-mailbox-getcallbacktokenasync-member(2)) | ReadItem | Compose<br>Read | [1.3](../requirement-set-1.3/outlook-requirement-set-1.3.md)<br>[1.1](../requirement-set-1.1/outlook-requirement-set-1.1.md) |
```

2022-02-02 02:06 UTC, ElizabethSamuel-MSFT commented on docs/reference/objectmodel/requirement-set-1.9/office.context.mailbox.md
> +| [getCallbackTokenAsync(callback, [userContext])](/javascript/api/outlook/office.mailbox?view=outlook-js-1.9&preserve-view=true#outlook-office-mailbox-getcallbacktokenasync-member(1)) | ReadItem | C
```suggestion
| [getCallbackTokenAsync(callback, [userContext])](/javascript/api/outlook/office.mailbox?view=outlook-js-1.9&preserve-view=true#outlook-office-mailbox-getcallbacktokenasync-member(2)) | ReadItem | Compose<br>Read | [1.3](../requirement-set-1.3/outlook-requirement-set-1.3.md)<br>[1.1](../requirement-set-1.1/outlook-requirement-set-1.1.md) |
```

2022-02-02 02:06 UTC, ElizabethSamuel-MSFT commented on docs/outlook/authentication.md
> +Your add-in can call [getUserIdentityTokenAsync](/javascript/api/outlook/office.mailbox#outlook-office-mailbox-getcallbacktokenasync-member(1)) to get Exchange user identity tokens. For details on us
```suggestion
Your add-in can call [getUserIdentityTokenAsync](/javascript/api/outlook/office.mailbox#outlook-office-mailbox-getuseridentitytokenasync-member(1)) to get Exchange user identity tokens. For details on using these tokens, see [Authenticate a user with an identity token for Exchange](authenticate-a-user-with-an-identity-token.md).
```

2022-02-02 18:35 UTC, opbld31 commented
Docs Build status updates of commit _[cd4ae26](https://github.com/OfficeDev/office-js-docs-pr/commits/cd4ae260f45268f3770e32b1cc8d9d6fe3202337)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/concepts/add-in-development-best-practices.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/concepts/add-in-development-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/concepts/add-in-development-best-practices?branch=pr-en-us-3213) |
[docs/concepts/resource-limits-and-performance-optimization.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/concepts/resource-limits-and-performance-optimization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/concepts/resource-limits-and-performance-optimization?branch=pr-en-us-3213) |
[docs/design/contextual-tabs.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/design/contextual-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/design/contextual-tabs?branch=pr-en-us-3213) |
[docs/design/disable-add-in-commands.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/design/disable-add-in-commands.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/design/disable-add-in-commands?branch=pr-en-us-3213) |
[docs/design/keyboard-shortcuts.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/design/keyboard-shortcuts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/design/keyboard-shortcuts?branch=pr-en-us-3213) |
[docs/develop/add-in-manifests.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/add-in-manifests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/add-in-manifests?branch=pr-en-us-3213) |
[docs/develop/application-specific-api-model.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/application-specific-api-model.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/application-specific-api-model?branch=pr-en-us-3213) |
[docs/develop/asynchronous-programming-in-office-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/asynchronous-programming-in-office-add-ins.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/asynchronous-programming-in-office-add-ins?branch=pr-en-us-3213) |
[docs/develop/auth-with-office-dialog-api.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/auth-with-office-dialog-api.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/auth-with-office-dialog-api?branch=pr-en-us-3213) |
[docs/develop/authorize-to-microsoft-graph.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/authorize-to-microsoft-graph.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/authorize-to-microsoft-graph?branch=pr-en-us-3213) |
[docs/develop/develop-office-add-ins-for-the-ipad.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/develop-office-add-ins-for-the-ipad.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/develop-office-add-ins-for-the-ipad?branch=pr-en-us-3213) |
[docs/develop/dialog-api-in-office-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/dialog-api-in-office-add-ins.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/dialog-api-in-office-add-ins?branch=pr-en-us-3213) |
[docs/develop/dialog-best-practices.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/dialog-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/dialog-best-practices?branch=pr-en-us-3213) |
[docs/develop/office-javascript-api-object-model.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/office-javascript-api-object-model.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/office-javascript-api-object-model?branch=pr-en-us-3213) |
[docs/develop/overview-authn-authz.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/overview-authn-authz.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/overview-authn-authz?branch=pr-en-us-3213) |
[docs/develop/persisting-add-in-state-and-settings.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/persisting-add-in-state-and-settings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/persisting-add-in-state-and-settings?branch=pr-en-us-3213) |
[docs/develop/read-and-write-data-to-the-active-selection-in-a-document-or-spreadsheet.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/read-and-write-data-to-the-active-selection-in-a-document-or-spreadsheet.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/read-and-write-data-to-the-active-selection-in-a-document-or-spreadsheet?branch=pr-en-us-3213) |
[docs/develop/requesting-permissions-for-api-use-in-content-and-task-pane-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/requesting-permissions-for-api-use-in-content-and-task-pane-add-ins.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/requesting-permissions-for-api-use-in-content-and-task-pane-add-ins?branch=pr-en-us-3213) |
[docs/develop/show-hide-add-in.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/show-hide-add-in.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/show-hide-add-in?branch=pr-en-us-3213) |
[docs/develop/specify-office-hosts-and-api-requirements.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/specify-office-hosts-and-api-requirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/specify-office-hosts-and-api-requirements?branch=pr-en-us-3213) |
[docs/develop/sso-in-office-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/sso-in-office-add-ins.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/sso-in-office-add-ins?branch=pr-en-us-3213) |
[docs/develop/support-for-task-pane-and-content-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/support-for-task-pane-and-content-add-ins.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/support-for-task-pane-and-content-add-ins?branch=pr-en-us-3213) |
[docs/develop/troubleshoot-sso-in-office-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/troubleshoot-sso-in-office-add-ins.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/troubleshoot-sso-i [...]

2022-02-02 18:45 UTC, opbld31 commented
Docs Build status updates of commit _[2f93d55](https://github.com/OfficeDev/office-js-docs-pr/commits/2f93d55e4b181fc0194e1129be4544ae7867c837)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/concepts/add-in-development-best-practices.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/concepts/add-in-development-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/concepts/add-in-development-best-practices?branch=pr-en-us-3213) |
[docs/concepts/resource-limits-and-performance-optimization.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/concepts/resource-limits-and-performance-optimization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/concepts/resource-limits-and-performance-optimization?branch=pr-en-us-3213) |
[docs/design/contextual-tabs.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/design/contextual-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/design/contextual-tabs?branch=pr-en-us-3213) |
[docs/design/disable-add-in-commands.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/design/disable-add-in-commands.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/design/disable-add-in-commands?branch=pr-en-us-3213) |
[docs/design/keyboard-shortcuts.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/design/keyboard-shortcuts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/design/keyboard-shortcuts?branch=pr-en-us-3213) |
[docs/develop/add-in-manifests.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/add-in-manifests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/add-in-manifests?branch=pr-en-us-3213) |
[docs/develop/application-specific-api-model.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/application-specific-api-model.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/application-specific-api-model?branch=pr-en-us-3213) |
[docs/develop/asynchronous-programming-in-office-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/asynchronous-programming-in-office-add-ins.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/asynchronous-programming-in-office-add-ins?branch=pr-en-us-3213) |
[docs/develop/auth-with-office-dialog-api.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/auth-with-office-dialog-api.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/auth-with-office-dialog-api?branch=pr-en-us-3213) |
[docs/develop/authorize-to-microsoft-graph.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/authorize-to-microsoft-graph.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/authorize-to-microsoft-graph?branch=pr-en-us-3213) |
[docs/develop/develop-office-add-ins-for-the-ipad.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/develop-office-add-ins-for-the-ipad.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/develop-office-add-ins-for-the-ipad?branch=pr-en-us-3213) |
[docs/develop/dialog-api-in-office-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/dialog-api-in-office-add-ins.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/dialog-api-in-office-add-ins?branch=pr-en-us-3213) |
[docs/develop/dialog-best-practices.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/dialog-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/dialog-best-practices?branch=pr-en-us-3213) |
[docs/develop/office-javascript-api-object-model.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/office-javascript-api-object-model.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/office-javascript-api-object-model?branch=pr-en-us-3213) |
[docs/develop/overview-authn-authz.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/overview-authn-authz.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/overview-authn-authz?branch=pr-en-us-3213) |
[docs/develop/persisting-add-in-state-and-settings.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/persisting-add-in-state-and-settings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/persisting-add-in-state-and-settings?branch=pr-en-us-3213) |
[docs/develop/read-and-write-data-to-the-active-selection-in-a-document-or-spreadsheet.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/read-and-write-data-to-the-active-selection-in-a-document-or-spreadsheet.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/read-and-write-data-to-the-active-selection-in-a-document-or-spreadsheet?branch=pr-en-us-3213) |
[docs/develop/requesting-permissions-for-api-use-in-content-and-task-pane-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/requesting-permissions-for-api-use-in-content-and-task-pane-add-ins.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/requesting-permissions-for-api-use-in-content-and-task-pane-add-ins?branch=pr-en-us-3213) |
[docs/develop/show-hide-add-in.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/show-hide-add-in.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/show-hide-add-in?branch=pr-en-us-3213) |
[docs/develop/specify-office-hosts-and-api-requirements.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/specify-office-hosts-and-api-requirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/specify-office-hosts-and-api-requirements?branch=pr-en-us-3213) |
[docs/develop/sso-in-office-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/sso-in-office-add-ins.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/sso-in-office-add-ins?branch=pr-en-us-3213) |
[docs/develop/support-for-task-pane-and-content-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/support-for-task-pane-and-content-add-ins.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/support-for-task-pane-and-content-add-ins?branch=pr-en-us-3213) |
[docs/develop/troubleshoot-sso-in-office-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/troubleshoot-sso-in-office-add-ins.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/troubleshoot-sso-i [...]

2022-02-02 18:46 UTC, AlexJerabek commented
Thanks for taking a look @ElizabethSamuel-MSFT. I believe I either applied all your suggestions or fixed them with another regex pass. Please take another look at the recent commits when you can.

2022-02-02 19:54 UTC, ElizabethSamuel-MSFT approved these changes

2022-02-02 19:54 UTC, ElizabethSamuel-MSFT commented on docs/reference/requirement-sets/excel-api-1-13-requirement-set.md
> +| [Insert worksheets](../../excel//excel-add-ins-workbooks.md#insert-a-copy-of-an-existing-workbook-into-the-current-one) | Insert worksheets from another workbook into the current workbook as a Base
```suggestion
| [Insert worksheets](../../excel/excel-add-ins-workbooks.md#insert-a-copy-of-an-existing-workbook-into-the-current-one) | Insert worksheets from another workbook into the current workbook as a Base64-encoded string. | [Workbook.insertWorksheetsFromBase64](/javascript/api/excel/excel.workbook#excel-excel-workbook-insertworksheetsfrombase64-member(1)) |
```

2022-02-02 20:34 UTC, AlexJerabek commented on docs/reference/requirement-sets/excel-api-1-13-requirement-set.md
> +| [Insert worksheets](../../excel//excel-add-ins-workbooks.md#insert-a-copy-of-an-existing-workbook-into-the-current-one) | Insert worksheets from another workbook into the current workbook as a Base
```suggestion
| [Insert worksheets](../../excel/excel-add-ins-workbooks.md#insert-a-copy-of-an-existing-workbook-into-the-current-one) | Insert worksheets from another workbook into the current workbook as a Base64-encoded string. | [Workbook.insertWorksheetsFromBase64](/javascript/api/excel/excel.workbook#excel-excel-workbook-insertworksheetsfrombase64-member(1)) |
```

2022-02-02 20:41 UTC, opbld31 commented
Docs Build status updates of commit _[ab54baf](https://github.com/OfficeDev/office-js-docs-pr/commits/ab54bafed0bdc380a7e97ac60fb2c2ad836802a5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/concepts/add-in-development-best-practices.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/concepts/add-in-development-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/concepts/add-in-development-best-practices?branch=pr-en-us-3213) |
[docs/concepts/resource-limits-and-performance-optimization.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/concepts/resource-limits-and-performance-optimization.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/concepts/resource-limits-and-performance-optimization?branch=pr-en-us-3213) |
[docs/design/contextual-tabs.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/design/contextual-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/design/contextual-tabs?branch=pr-en-us-3213) |
[docs/design/disable-add-in-commands.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/design/disable-add-in-commands.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/design/disable-add-in-commands?branch=pr-en-us-3213) |
[docs/design/keyboard-shortcuts.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/design/keyboard-shortcuts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/design/keyboard-shortcuts?branch=pr-en-us-3213) |
[docs/develop/add-in-manifests.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/add-in-manifests.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/add-in-manifests?branch=pr-en-us-3213) |
[docs/develop/application-specific-api-model.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/application-specific-api-model.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/application-specific-api-model?branch=pr-en-us-3213) |
[docs/develop/asynchronous-programming-in-office-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/asynchronous-programming-in-office-add-ins.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/asynchronous-programming-in-office-add-ins?branch=pr-en-us-3213) |
[docs/develop/auth-with-office-dialog-api.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/auth-with-office-dialog-api.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/auth-with-office-dialog-api?branch=pr-en-us-3213) |
[docs/develop/authorize-to-microsoft-graph.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/authorize-to-microsoft-graph.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/authorize-to-microsoft-graph?branch=pr-en-us-3213) |
[docs/develop/develop-office-add-ins-for-the-ipad.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/develop-office-add-ins-for-the-ipad.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/develop-office-add-ins-for-the-ipad?branch=pr-en-us-3213) |
[docs/develop/dialog-api-in-office-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/dialog-api-in-office-add-ins.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/dialog-api-in-office-add-ins?branch=pr-en-us-3213) |
[docs/develop/dialog-best-practices.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/dialog-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/dialog-best-practices?branch=pr-en-us-3213) |
[docs/develop/office-javascript-api-object-model.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/office-javascript-api-object-model.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/office-javascript-api-object-model?branch=pr-en-us-3213) |
[docs/develop/overview-authn-authz.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/overview-authn-authz.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/overview-authn-authz?branch=pr-en-us-3213) |
[docs/develop/persisting-add-in-state-and-settings.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/persisting-add-in-state-and-settings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/persisting-add-in-state-and-settings?branch=pr-en-us-3213) |
[docs/develop/read-and-write-data-to-the-active-selection-in-a-document-or-spreadsheet.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/read-and-write-data-to-the-active-selection-in-a-document-or-spreadsheet.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/read-and-write-data-to-the-active-selection-in-a-document-or-spreadsheet?branch=pr-en-us-3213) |
[docs/develop/requesting-permissions-for-api-use-in-content-and-task-pane-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/requesting-permissions-for-api-use-in-content-and-task-pane-add-ins.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/requesting-permissions-for-api-use-in-content-and-task-pane-add-ins?branch=pr-en-us-3213) |
[docs/develop/show-hide-add-in.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/show-hide-add-in.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/show-hide-add-in?branch=pr-en-us-3213) |
[docs/develop/specify-office-hosts-and-api-requirements.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/specify-office-hosts-and-api-requirements.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/specify-office-hosts-and-api-requirements?branch=pr-en-us-3213) |
[docs/develop/sso-in-office-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/sso-in-office-add-ins.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/sso-in-office-add-ins?branch=pr-en-us-3213) |
[docs/develop/support-for-task-pane-and-content-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/support-for-task-pane-and-content-add-ins.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/support-for-task-pane-and-content-add-ins?branch=pr-en-us-3213) |
[docs/develop/troubleshoot-sso-in-office-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/AlexJ-ReferenceLinks/docs/develop/troubleshoot-sso-in-office-add-ins.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/troubleshoot-sso-i [...]

2022-02-02 21:06 UTC, merged