Excel] (custom functions) remove 'UI-less' terminology
OfficeDev/office-js-docs-pr pull request #3496
Opened 2022-06-15 23:54 UTC by Rick-Kirkham

2022-06-15 23:54 UTC, opbld31 commented
Docs Build status updates of commit _[4d1041f](https://github.com/OfficeDev/office-js-docs-pr/commits/4d1041f9d04548d109287b7d120e11dbf856d48b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/develop/json-manifest-overview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/develop/json-manifest-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/json-manifest-overview?branch=pr-en-us-3496) |
[docs/excel/custom-functions-authentication.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/excel/custom-functions-authentication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-authentication?branch=pr-en-us-3496) |
[docs/excel/custom-functions-debugging.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/excel/custom-functions-debugging.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-debugging?branch=pr-en-us-3496) |
[docs/excel/custom-functions-runtime.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/excel/custom-functions-runtime.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-runtime?branch=pr-en-us-3496) |
[docs/includes/office-js-api-models.md](https://github.com/OfficeDev/office-js-docs-pr/blob/cf-terminology-change/docs/includes/office-js-api-models.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/develop-overview?branch=pr-en-us-3496) |
[docs/resources/resources-glossary.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/resources/resources-glossary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/resources/resources-glossary?branch=pr-en-us-3496) |
[docs/testing/debug-add-ins-overview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/testing/debug-add-ins-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/testing/debug-add-ins-overview?branch=pr-en-us-3496) |
[docs/toc.yml](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/json-manifest-overview?branch=pr-en-us-3496) |
[docs/tutorials/share-data-and-events-between-custom-functions-and-the-task-pane-tutorial.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/tutorials/share-data-and-events-between-custom-functions-and-the-task-pane-tutorial.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/tutorials/share-data-and-events-between-custom-functions-and-the-task-pane-tutorial?branch=pr-en-us-3496) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/57856ef7-e8cf-54ca-0d12-df5f42d1e8bb/202206152354050186-3496/BuildReport?accessString=ab8f8f186e905a09bfd95f1c6060aee8816e0f67f140ccc75c169000b355bb81).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/57856ef7-e8cf-54ca-0d12-df5f42d1e8bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-16 01:02 UTC, alison-mk approved these changes
Looks good! Thanks for making these changes. Left comments about a couple very minor changes, and one question.

2022-06-16 02:20 UTC, opbld31 commented
Docs Build status updates of commit _[338ba41](https://github.com/OfficeDev/office-js-docs-pr/commits/338ba41b78188f22d99518522b516f6869bd81e5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/develop/json-manifest-overview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/develop/json-manifest-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/json-manifest-overview?branch=pr-en-us-3496) |
[docs/excel/custom-functions-authentication.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/excel/custom-functions-authentication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-authentication?branch=pr-en-us-3496) |
[docs/excel/custom-functions-debugging.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/excel/custom-functions-debugging.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-debugging?branch=pr-en-us-3496) |
[docs/excel/custom-functions-runtime.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/excel/custom-functions-runtime.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-runtime?branch=pr-en-us-3496) |
[docs/includes/office-js-api-models.md](https://github.com/OfficeDev/office-js-docs-pr/blob/cf-terminology-change/docs/includes/office-js-api-models.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/develop-overview?branch=pr-en-us-3496) |
[docs/resources/resources-glossary.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/resources/resources-glossary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/resources/resources-glossary?branch=pr-en-us-3496) |
[docs/testing/debug-add-ins-overview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/testing/debug-add-ins-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/testing/debug-add-ins-overview?branch=pr-en-us-3496) |
[docs/toc.yml](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/json-manifest-overview?branch=pr-en-us-3496) |
[docs/tutorials/share-data-and-events-between-custom-functions-and-the-task-pane-tutorial.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/tutorials/share-data-and-events-between-custom-functions-and-the-task-pane-tutorial.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/tutorials/share-data-and-events-between-custom-functions-and-the-task-pane-tutorial?branch=pr-en-us-3496) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/57856ef7-e8cf-54ca-0d12-df5f42d1e8bb/202206160220002722-3496/BuildReport?accessString=d9ad725add05c426aadc7cd4ac4ef7d94f85dd82b9e20ec99a4a24fc25953465).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/57856ef7-e8cf-54ca-0d12-df5f42d1e8bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-16 02:22 UTC, Rick-Kirkham commented on docs/toc.yml
> +    - name: Custom functions without a shared runtime
I'd say yes, since it is about debugging only custom functions without a shared runtime. But I'll leave that to you.

2022-06-17 22:44 UTC, davidchesnut requested changes

2022-06-17 22:45 UTC, davidchesnut reviewed
I really like the phrasing of "custom functions without a shared runtime." Perfect rename!

2022-06-17 23:08 UTC, Rick-Kirkham commented on docs/resources/resources-glossary.md
> +An add-in that contains a custom function, but no UI such as a task pane. The custom functions in this kind of add-in run in a JavaScript-only runtime. A custom function that does include a UI can us
```suggestion
An add-in that contains a custom function, but no UI such as a task pane. The custom functions in this kind of add-in run in a JavaScript-only runtime. A custom function that does include a UI can use either a shared runtime or a combination of a JavaScript-only runtime and an HTML-supporting runtime. We recommend that if you have a UI, you use a shared runtime. 
```

2022-06-17 23:11 UTC, opbld30 commented
Docs Build status updates of commit _[9e30a9f](https://github.com/OfficeDev/office-js-docs-pr/commits/9e30a9f02418231b5feb30f1d8ae77b0779e967b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/develop/json-manifest-overview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/develop/json-manifest-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/json-manifest-overview?branch=pr-en-us-3496) |
[docs/excel/custom-functions-authentication.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/excel/custom-functions-authentication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-authentication?branch=pr-en-us-3496) |
[docs/excel/custom-functions-debugging.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/excel/custom-functions-debugging.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-debugging?branch=pr-en-us-3496) |
[docs/excel/custom-functions-runtime.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/excel/custom-functions-runtime.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-runtime?branch=pr-en-us-3496) |
[docs/includes/office-js-api-models.md](https://github.com/OfficeDev/office-js-docs-pr/blob/cf-terminology-change/docs/includes/office-js-api-models.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/develop-overview?branch=pr-en-us-3496) |
[docs/resources/resources-glossary.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/resources/resources-glossary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/resources/resources-glossary?branch=pr-en-us-3496) |
[docs/testing/debug-add-ins-overview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/testing/debug-add-ins-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/testing/debug-add-ins-overview?branch=pr-en-us-3496) |
[docs/toc.yml](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/develop/json-manifest-overview?branch=pr-en-us-3496) |
[docs/tutorials/share-data-and-events-between-custom-functions-and-the-task-pane-tutorial.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/tutorials/share-data-and-events-between-custom-functions-and-the-task-pane-tutorial.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/office/dev/add-ins/tutorials/share-data-and-events-between-custom-functions-and-the-task-pane-tutorial?branch=pr-en-us-3496) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/57856ef7-e8cf-54ca-0d12-df5f42d1e8bb/202206172310443368-3496/BuildReport?accessString=427a08249a4743c9964c3c56b2bc6ae729085822b666c3019db9d99a2fcdb318).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/57856ef7-e8cf-54ca-0d12-df5f42d1e8bb?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-21 22:39 UTC, merged