[Word] (tutorial) Refresh
OfficeDev/office-js-docs-pr pull request #3900
Opened 2023-03-10 21:43 UTC by ElizabethSamuel-MSFT

2023-03-10 23:04 UTC, AlexJerabek requested changes

2023-03-10 23:05 UTC, AlexJerabek commented
(@ElizabethSamuel-MSFT, apologies that some of the comments are not on the lines they correspond to. GitHub wouldn't let me be more helpful.

2023-03-14 17:28 UTC, ElizabethSamuel-MSFT commented on docs/tutorials/word-tutorial.md
Updated

2023-03-14 20:56 UTC, AlexJerabek approved these changes
Approving with a couple minor suggestions.

2023-03-14 20:56 UTC, AlexJerabek commented on docs/tutorials/word-tutorial.md
> +   - Your Word.js business logic will be added to the function that's passed to `Word.run`. This logic doesn't execute immediately. Instead, it's added to a queue of pending commands.
```suggestion
   - Your Word.js business logic will be added to the function passed to `Word.run`. This logic doesn't execute immediately. Instead, it's added to a queue of pending commands.
```

2023-03-14 20:56 UTC, AlexJerabek commented on docs/tutorials/word-tutorial.md
> +   - The `tryCatch` function will be used by all the functions interacting with the workbook from the task pane. Catching Office JavaScript errors in this fashion is a convenient way to generically h
```suggestion
   - The `tryCatch` function will be used by all the functions interacting with the workbook from the task pane. Catching Office JavaScript errors in this fashion is a convenient way to generically handle uncaught errors.
```

2023-03-14 21:10 UTC, merged