Update register-sso-add-in-aad-v2.md
OfficeDev/office-js-docs-pr pull request #4245
Opened 2023-11-01 20:20 UTC by mattgeim

2023-11-07 17:59 UTC, davidchesnut commented on docs/develop/register-sso-add-in-aad-v2.md
> +> [!IMPORTANT]
```suggestion
> [!CAUTION]
```

Use caution for potential negative consequences.

2023-11-07 18:00 UTC, davidchesnut commented on docs/develop/register-sso-add-in-aad-v2.md
> +> **Sensitive information**: The application ID URI (`<fully-qualified-domain-name>`) is logged as part of the authentication process when an add-in using SSO is activated in Office running inside of
```suggestion
> **Sensitive information**: The application ID URI (`<fully-qualified-domain-name>`) is logged as part of the authentication process when an add-in using SSO is activated in Office running inside of Microsoft Teams. The URI mustn't contain sensitive information.
```

2023-11-07 18:01 UTC, davidchesnut requested changes
Looks good, just a couple suggestions, thanks!

2023-11-10 00:20 UTC, davidchesnut requested changes
A few suggested changes. Thanks!

2023-11-10 00:20 UTC, davidchesnut commented on docs/includes/register-sso-add-in-aad-v2-include.md
> +1. In the **Client ID** enter `ea5a67f6-b6f3-4338-b240-c655ddc3cc8e`. This value pre-authorizes all Microsoft Office application endpoints. If you also would like to pre-authorize Office when used in
```suggestion
1. In the **Client ID** enter `ea5a67f6-b6f3-4338-b240-c655ddc3cc8e`. This value pre-authorizes all Microsoft Office application endpoints. If you also want to pre-authorize Office when used inside of Microsoft Teams, add `1fec8e78-bce4-4aaf-ab1b-5451cc387264` (Microsoft Teams desktop and Teams mobile) and `5e3ce6c0-2b1f-4285-8d4b-75ee78787346` (Teams on the web).
```

2023-11-10 00:53 UTC, mattgeim reviewed
.

2023-11-10 00:54 UTC, merged