[All hosts] (publishing) Add information on creating an install link
OfficeDev/office-js-docs-pr pull request #4588
Opened 2024-05-24 17:22 UTC by davidchesnut

This adds information on how to create an install link for your add-in. Also removes the direct link to the Microsoft AppSource publishing page and instead provides a brief overview in this content library.

2024-05-24 21:44 UTC, lindalu-MSFT requested changes

2024-05-24 21:44 UTC, lindalu-MSFT commented on docs/publish/publish-office-add-ins-to-appsource.md
> +## Provide an install link
Agree!
```suggestion
## Provide an installation link
```

2024-05-24 21:44 UTC, lindalu-MSFT commented on docs/publish/publish-office-add-ins-to-appsource.md
> +After you publish to Microsoft AppSource, you can create an install link to help customers discover and install your add-in. The install link provides a "click and run" experience. Put the link on yo
```suggestion
After you publish to Microsoft AppSource, you can create an installation link to help customers discover and install your add-in. The installation link provides a "click and run" experience. Put the link on your website, social media, or anywhere you think helps your customers discover your add-in.
```
Do we want to say "your customers and others"?

2024-05-24 21:44 UTC, lindalu-MSFT commented on docs/publish/publish-office-add-ins-to-appsource.md
> +For example, if you want to provide an install link for [Script Lab](https://appsource.microsoft.com/product/office/wa104380862), use the following link.
```suggestion
For example, if you want to provide an installation link for [Script Lab](https://appsource.microsoft.com/product/office/wa104380862), use the following link.
```

2024-05-24 21:44 UTC, lindalu-MSFT commented on docs/publish/publish-office-add-ins-to-appsource.md
> +The following parameter values are used for the Script Lab install link.
```suggestion
The following parameter values are used for the Script Lab installation link.
```

2024-05-30 05:20 UTC, Rick-Kirkham approved these changes

2024-05-30 21:54 UTC, merged