Update Fabric Core URLs which were blocked by CORS policy
OfficeDev/office-js-docs-pr pull request #4808
Opened 2024-09-23 00:20 UTC by garysharp

This PR updates the stylesheet URLs for Fabric Core, in alignment with the current [Fabric Core documentation](https://developer.microsoft.com/en-us/fluentui#/get-started/web#fabric-core).

Sometime on 2024-09-18 the CORS policy changed for the files hosted on https://static2.sharepointonline.com.
![CORS-block](https://github.com/user-attachments/assets/d0c83923-9562-41ec-8c42-47b0beafb653)
This caused a broad outage for our Outlook Addin and users were prevented from sending specific emails. It would appear that the CORS policy has been reverted for now.

2024-09-23 00:24 UTC, garysharp commented
@microsoft-github-policy-service agree

2024-09-24 03:01 UTC, garysharp commented
Related: https://github.com/microsoft/fluentui/issues/32861

2024-09-26 20:06 UTC, samantharamon requested changes
Thank you for catching this and contributing to the docs, @garysharp! I added suggestions to also update the Fabric Core version in the URL. I'll merge the PR once you accept the changes.

2024-09-26 20:06 UTC, samantharamon commented on docs/design/fabric-core.md
> +    <link rel="stylesheet" href="https://res-1.cdn.office.net/files/fabric-cdn-prod_20230815.002/office-ui-fabric-core/9.6.1/css/fabric.min.css">
```suggestion
    <link rel="stylesheet" href="https://res-1.cdn.office.net/files/fabric-cdn-prod_20230815.002/office-ui-fabric-core/11.0.0/css/fabric.min.css">
```
Also taking this opportunity to update the Fabric Core version.

2024-09-26 20:06 UTC, samantharamon commented on docs/tutorials/excel-tutorial.md
> +            <link rel="stylesheet" href="https://res-1.cdn.office.net/files/fabric-cdn-prod_20230815.002/office-ui-fabric-core/9.6.1/css/fabric.min.css"/>
```suggestion
            <link rel="stylesheet" href="https://res-1.cdn.office.net/files/fabric-cdn-prod_20230815.002/office-ui-fabric-core/11.0.0/css/fabric.min.css"/>
```

2024-09-26 20:06 UTC, samantharamon commented on docs/tutorials/outlook-tutorial.md
> +      <link rel="stylesheet" href="https://res-1.cdn.office.net/files/fabric-cdn-prod_20230815.002/office-ui-fabric-core/9.6.1/css/fabric.min.css"/>
```suggestion
      <link rel="stylesheet" href="https://res-1.cdn.office.net/files/fabric-cdn-prod_20230815.002/office-ui-fabric-core/11.0.0/css/fabric.min.css"/>
```

2024-09-26 20:06 UTC, samantharamon commented on docs/tutorials/outlook-tutorial.md
> +        <link rel="stylesheet" href="https://res-1.cdn.office.net/files/fabric-cdn-prod_20230815.002/office-ui-fabric-core/9.6.1/css/fabric.min.css"/>
```suggestion
        <link rel="stylesheet" href="https://res-1.cdn.office.net/files/fabric-cdn-prod_20230815.002/office-ui-fabric-core/11.0.0/css/fabric.min.css"/>
```

2024-09-27 16:53 UTC, merged